import { DEFAULT_MANAGED_MODEL_IDS } from '@kortix/llm-catalog';

export const MANAGED_MODEL_ID_SET = new Set<string>(DEFAULT_MANAGED_MODEL_IDS);

export const CODEX_AUTH_JSON_SECRET_NAME = 'CODEX_AUTH_JSON';
export const LEGACY_OPENCODE_AUTH_JSON_SECRET_NAME = 'OPENCODE_AUTH_JSON';
export const CLAUDE_CODE_OAUTH_TOKEN_SECRET_NAME = 'CLAUDE_CODE_OAUTH_TOKEN';
export const CUSTOM_LLM_SECRET_NAMES = [
  'CUSTOM_LLM_PROTOCOL',
  'CUSTOM_LLM_BASE_URL',
  'CUSTOM_LLM_API_KEY',
  'CUSTOM_LLM_MODEL_ID',
  'CUSTOM_LLM_NAME',
] as const;
