/**
 * Golden parity harness for the OpenCode-wire projection stack
 * (`./transcript` + `core/turns/*`) — see the `@deprecated` tags on those
 * modules. This stack is frozen, not removed: the ACTIVE conversation
 * surface (`apps/web`'s `acp-session-chat`) renders exclusively from the
 * ACP engine (`acp/reduce.ts` + `acp/transcript.ts`), and the OpenCode-wire
 * stack today only serves session-list previews, `?oc` deep-links, and
 * `apps/mobile`. A future removal of this stack must reproduce these exact
 * outputs for any host that still depends on it, or explicitly migrate that
 * host first — that is the whole point of pinning it here.
 *
 * The fixture (`core/turns/__fixtures__/opencode-wire-mixed.json`) is a
 * `{session, messages}` shape exercising every wire `Part` variant (text,
 * reasoning, tool ×3 — read/bash/web_search-embedded-failure —, file,
 * subtask, patch, snapshot, agent, retry, compaction, step-start,
 * step-finish), an assistant message carrying `info.error`, and an empty
 * turn (step-start only, no visible content) — the shapes the classify /
 * view-model / transcript layers all branch on.
 *
 * The golden JSON/MD files were generated by running the CURRENT
 * implementation over that fixture (characterization, not hand-computed
 * expectations) — see git history for the generation script. A diff here
 * means the frozen stack's behavior changed; that is exactly the signal
 * this harness exists to raise before any retirement work proceeds.
 */
import { describe, expect, test } from 'bun:test';

import fixture from './core/turns/__fixtures__/opencode-wire-mixed.json';
import classifiedGolden from './core/turns/__fixtures__/opencode-wire-classified.golden.json';
import toolViewsGolden from './core/turns/__fixtures__/opencode-wire-tool-views.golden.json';
import { classifyTurn, type ClassifiedPart } from './core/turns/classify';
import { toolViewModel } from './core/turns/view-model';
import { DEFAULT_TRANSCRIPT_OPTIONS, formatTranscript, type MessageWithParts, type SessionInfo } from './transcript';

const session = fixture.session as SessionInfo;
const messages = fixture.messages as unknown as MessageWithParts[];

describe('OpenCode-wire projection stack — golden parity (frozen, not removed)', () => {
  test('classifyTurn output matches the frozen golden for every fixture message', () => {
    const classified = messages.map((m) => classifyTurn(m));
    expect(classified).toEqual(classifiedGolden as unknown as typeof classified);
  });

  test('toolViewModel output matches the frozen golden for every classified tool part', () => {
    const classified = messages.map((m) => classifyTurn(m));
    const toolViews: unknown[] = [];
    for (const turn of classified) {
      for (const part of turn.parts as ClassifiedPart[]) {
        if (part.kind === 'tool') toolViews.push(toolViewModel(part.tool));
      }
    }
    expect(toolViews).toEqual(toolViewsGolden as unknown as typeof toolViews);
  });

  test('formatTranscript body matches the frozen golden (header excluded — its Created/Updated lines run through the platform locale/timezone, which is not fair to freeze across CI runners)', async () => {
    const md = formatTranscript(session, messages, DEFAULT_TRANSCRIPT_OPTIONS);
    const separator = '---\n\n';
    const headerEnd = md.indexOf(separator);
    expect(headerEnd).toBeGreaterThan(-1);
    const body = md.slice(headerEnd + separator.length);

    const goldenPath = new URL('./core/turns/__fixtures__/opencode-wire-transcript-body.golden.md', import.meta.url);
    const golden = await Bun.file(goldenPath).text();
    expect(body).toBe(golden);
  });

  test('formatTranscript header still carries the session title and id (freezing content, not locale-dependent formatting)', () => {
    const md = formatTranscript(session, messages, DEFAULT_TRANSCRIPT_OPTIONS);
    expect(md).toContain('# Fix the flaky login test');
    expect(md).toContain('**Session ID:** `ses_abc123`');
  });
});
