// Main exports
export { createDb, type Database } from './client';
export * as schema from './schema';

// Re-export frequently used schemas and types for convenience
export {
  // Schema namespace
  kortixSchema,
  // Enums
  sandboxStatusEnum,
  deploymentStatusEnum,
  deploymentSourceEnum,
  projectStatusEnum,
  projectSessionStatusEnum,
  projectSnapshotStatusEnum,
  projectRoleEnum,
  projectTriggerTypeEnum,
  projectTriggerEventStatusEnum,
  apiKeyStatusEnum,
  apiKeyTypeEnum,
  // Kortix tables — accounts
  accounts,
  accountMembers,
  accountInvitations,
  accountGithubInstallations,
  accountRoleEnum,
  accountsRelations,
  accountMembersRelations,
  accountGithubInstallationsRelations,
  auditEvents,
  usageEvents,
  // Kortix tables
  projects,
  projectMembers,
  projectSecrets,
  projectOauthCredentials,
  projectTriggers,
  projectTriggerEvents,
  projectTriggerRuntime,
  projectSessions,
  projectRuntimeSnapshots,
  sessionSandboxes,
  sessionSandboxStatusEnum,
  sandboxes,
  sandboxMembers,
  sandboxMemberScopes,
  scopeEffectEnum,
  sandboxInvites,
  legacySandboxMigrations,
  deployments,
  kortixApiKeys,
  serverEntries,
  // Relations
  projectsRelations,
  projectMembersRelations,
  projectSecretsRelations,
  projectOauthCredentialsRelations,
  projectTriggersRelations,
  projectTriggerEventsRelations,
  projectSessionsRelations,
  projectRuntimeSnapshotsRelations,
  sandboxesRelations,
  sandboxMembersRelations,
  sandboxInvitesRelations,
  deploymentsRelations,
  kortixApiKeysRelations,
  // Billing / Credits (moved from public → kortix schema)
  billingCustomers,
  creditAccounts,
  creditLedger,
  creditUsage,
  accountDeletionRequests,
  creditPurchases,
  // Tunnel
  tunnelStatusEnum,
  tunnelCapabilityEnum,
  tunnelPermissionStatusEnum,
  tunnelPermissionRequestStatusEnum,
  tunnelConnections,
  tunnelPermissions,
  tunnelPermissionRequests,
  tunnelAuditLogs,
  tunnelDeviceAuthStatusEnum,
  tunnelDeviceAuthRequests,
  tunnelConnectionsRelations,
  tunnelPermissionsRelations,
  tunnelPermissionRequestsRelations,
  tunnelAuditLogsRelations,
  // OAuth2 Provider
  oauthClients,
  oauthAuthorizationCodes,
  oauthAccessTokens,
  oauthRefreshTokens,
  // Platform User Roles
  platformRoleEnum,
  platformUserRoles,
  // Access Control
  accessRequestStatusEnum,
  platformSettings,
  accessAllowlist,
  accessRequests,
  // Pool
  poolResources,
  poolSandboxes,
} from './schema/kortix';

export type {
  TunnelMachineInfo,
  TunnelFilesystemScope,
  TunnelShellScope,
  TunnelNetworkScope,
  TunnelPermissionScope,
} from './schema/kortix';

// Public/basejump tables
export {
  apiKeys,
  accountUser,
  billingCustomersInBasejump,
} from './schema/public';

export type {
  Account,
  AccountMember,
  NewAccount,
  NewAccountMember,
  Project,
  NewProject,
  ProjectMember,
  NewProjectMember,
  ProjectSecret,
  NewProjectSecret,
  ProjectTrigger,
  NewProjectTrigger,
  ProjectTriggerEvent,
  NewProjectTriggerEvent,
  ProjectSession,
  NewProjectSession,
  ProjectRuntimeSnapshot,
  NewProjectRuntimeSnapshot,
  Sandbox,
  NewSandbox,
  SessionSandbox,
  NewSessionSandbox,
  ApiKey,
  CreditAccount,
  AccountUser,
  NewApiKey,
  SandboxSelect,
  KortixApiKey,
  NewKortixApiKey,
  ServerEntry,
  NewServerEntry,
  TunnelConnection,
  NewTunnelConnection,
  TunnelPermission,
  NewTunnelPermission,
  TunnelPermissionRequest,
  NewTunnelPermissionRequest,
  TunnelAuditLog,
  NewTunnelAuditLog,
} from './types';
