// Main exports
export { createDb, type Database } from './client';
export * as schema from './schema';

// Re-export frequently used schemas and types for convenience
export {
  // Schema namespace
  kortixSchema,
  // Enums
  sandboxStatusEnum,
  deploymentStatusEnum,
  deploymentSourceEnum,
  projectStatusEnum,
  projectSessionStatusEnum,
  projectRoleEnum,
  apiKeyStatusEnum,
  apiKeyTypeEnum,
  // Kortix tables — accounts
  accounts,
  accountMembers,
  accountInvitations,
  accountGithubInstallations,
  accountGithubInstallationStates,
  accountRoleEnum,
  accountsRelations,
  accountMembersRelations,
  accountGithubInstallationsRelations,
  auditEvents,
  usageEvents,
  // Kortix tables
  projects,
  projectGitConnections,
  projectGitCredentials,
  projectMembers,
  projectSecrets,
  projectSecretGrants,
  secretShareScopeEnum,
  secretGrantPrincipalEnum,
  projectSecretScopeEnum,
  projectTriggerRuntime,
  chatChannelBindings,
  chatInstalls,
  chatThreads,
  chatTurnStreams,
  chatEventDedup,
  projectSessions,
  projectSessionGrants,
  projectSessionVisibilityEnum,
  projectSnapshotBuilds,
  sandboxTemplates,
  sessionSandboxes,
  sessionSandboxStatusEnum,
  sandboxes,
  sandboxMembers,
  sandboxMemberScopes,
  scopeEffectEnum,
  sandboxInvites,
  legacySandboxMigrations,
  deployments,
  kortixApiKeys,
  accountTokens,
  serverEntries,
  // Relations
  projectsRelations,
  projectGitConnectionsRelations,
  projectGitCredentialsRelations,
  projectMembersRelations,
  projectSecretsRelations,
  projectSessionsRelations,
  sandboxesRelations,
  sandboxMembersRelations,
  sandboxInvitesRelations,
  deploymentsRelations,
  kortixApiKeysRelations,
  // Billing / Credits (moved from public → kortix schema)
  billingCustomers,
  creditAccounts,
  creditLedger,
  creditUsage,
  accountDeletionRequests,
  creditPurchases,
  // Billing v2 — per-seat + compute metering + per-member YOLO
  sandboxComputeSessions,
  yoloMemberTokens,
  stripeWebhookEventsProcessed,
  // Tunnel
  tunnelStatusEnum,
  tunnelCapabilityEnum,
  tunnelPermissionStatusEnum,
  tunnelPermissionRequestStatusEnum,
  tunnelConnections,
  tunnelPermissions,
  tunnelPermissionRequests,
  tunnelAuditLogs,
  tunnelDeviceAuthStatusEnum,
  tunnelDeviceAuthRequests,
  tunnelConnectionsRelations,
  tunnelPermissionsRelations,
  tunnelPermissionRequestsRelations,
  tunnelAuditLogsRelations,
  // OAuth2 Provider
  oauthClients,
  oauthAuthorizationCodes,
  oauthAccessTokens,
  oauthRefreshTokens,
  // Platform User Roles
  platformRoleEnum,
  platformUserRoles,
  // Access Control
  accessRequestStatusEnum,
  platformSettings,
  accessAllowlist,
  accessRequests,
  // Pool
  poolResources,
  poolSandboxes,
  // Change Requests
  changeRequestStatusEnum,
  changeRequests,
  changeRequestsRelations,
  // IAM
  accountGroupSourceEnum,
  accountGroups,
  accountGroupMembers,
  projectGroupGrants,
  accountGroupsRelations,
  accountGroupMembersRelations,
  // SCIM
  scimTokens,
  // Audit webhooks
  auditWebhooks,
  // SAML SSO
  accountSsoProviders,
  accountSsoGroupMappings,
  // Session policy
  accountSessionActivity,
  // Service accounts
  serviceAccounts,
  // Executor (connectors)
  executorConnectorProviderEnum,
  executorConnectorStatusEnum,
  executorPolicyActionEnum,
  executorRiskEnum,
  executorExecutionStatusEnum,
  executorCredentialModeEnum,
  executorConnectors,
  executorConnectorGrants,
  executorCredentials,
  executorConnectorActions,
  executorConnectorPolicies,
  executorProjectPolicies,
  executorProjectSettings,
  executorExecutions,
  executorConnectorsRelations,
  executorConnectorActionsRelations,
  executorConnectorPoliciesRelations,
  executorProjectPoliciesRelations,
  executorProjectSettingsRelations,
  projectSecretGrantsRelations,
} from './schema/kortix';

export type {
  TunnelMachineInfo,
  TunnelFilesystemScope,
  TunnelShellScope,
  TunnelNetworkScope,
  TunnelPermissionScope,
} from './schema/kortix';

// Public/basejump tables
export {
  apiKeys,
  accountUser,
  billingCustomersInBasejump,
} from './schema/public';

export type {
  Account,
  AccountMember,
  NewAccount,
  NewAccountMember,
  Project,
  NewProject,
  ProjectMember,
  NewProjectMember,
  ProjectSecret,
  NewProjectSecret,
  ChatChannelBinding,
  NewChatChannelBinding,
  ChatThread,
  NewChatThread,
  ProjectSession,
  NewProjectSession,
  ProjectSnapshotBuild,
  NewProjectSnapshotBuild,
  SandboxTemplate as DbSandboxTemplate,
  NewSandboxTemplate as NewDbSandboxTemplate,
  Sandbox,
  NewSandbox,
  SessionSandbox,
  NewSessionSandbox,
  ApiKey,
  CreditAccount,
  AccountUser,
  NewApiKey,
  SandboxSelect,
  KortixApiKey,
  NewKortixApiKey,
  ServerEntry,
  NewServerEntry,
  TunnelConnection,
  NewTunnelConnection,
  TunnelPermission,
  NewTunnelPermission,
  TunnelPermissionRequest,
  NewTunnelPermissionRequest,
  TunnelAuditLog,
  NewTunnelAuditLog,
} from './types';
