#!/usr/bin/env bash
# Rebuild MEMORY.md, the ledger index, from entries/.
#
#   index.sh           write MEMORY.md
#   index.sh --check   exit 1 when MEMORY.md does not match entries/
#
# MEMORY.md is generated. It lists every entry newest first, by the recorded
# timestamp in its filename, with the title from its `# ` heading.
set -euo pipefail
export LC_ALL=C

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

render() {
  cat <<'EOF'
# Learnings ledger

The episodic memory of this repository: one entry per incident or near-miss,
newest first. Each line is the time the entry was recorded (UTC) and its rule.
Open the entry for the incident, the trigger surface, and the enforcement.

Generated by `scripts/index.sh` from `entries/`. Do not edit by hand.

EOF
  # One awk pass over every entry, newest first: the recorded stamp comes from
  # the filename, the title from the first '# ' line.
  set -o pipefail
  find "$dir/entries" -maxdepth 1 -name '*.md' | sort -r | tr '\n' '\0' |
    xargs -0 awk '
      function untitled(file) { print "index.sh: " file " has no # title line" > "/dev/stderr"; failed = 1 }
      FNR == 1 { if (prev != "" && !done) untitled(prev); prev = FILENAME; done = 0 }
      !done && /^# / {
        n = split(FILENAME, parts, "/"); name = parts[n]
        stamp = substr(name, 1, 10) " " substr(name, 12, 2) ":" substr(name, 14, 2) ":" substr(name, 16, 2) "Z"
        title = substr($0, 3); gsub(/\]/, "\\]", title)
        printf "- `%s` [%s](entries/%s)\n", stamp, title, name
        done = 1
      }
      END { if (prev != "" && !done) untitled(prev); exit failed }'
}

# --check compares lines, not their order. A GitHub squash merge of a branch
# that added an entry keeps its index line where the branch put it, below
# entries merged later, and no one can run index.sh between the merge and the
# push to main. Order drift is fixed by the next index.sh run (new-entry.sh
# runs it); a missing, extra, or retitled line still fails.
if [ "${1:-}" = "--check" ]; then
  if ! diff -u <(sort "$dir/MEMORY.md") <(render | sort) >/dev/null; then
    echo "MEMORY.md is stale. Run: .agents/skills/learnings/scripts/index.sh" >&2
    diff -u <(sort "$dir/MEMORY.md") <(render | sort) | head -20 >&2 || true
    exit 1
  fi
  exit 0
fi

render >"$dir/MEMORY.md"
