import { chmodSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { dirname, join } from 'node:path'

import { logger } from './logger'
import type { ProjectEnvStore } from './project-env'

// tmpfs (RAM-backed) so plaintext secrets never land on the persisted container
// disk — Daytona hibernate/archive keeps the disk, /dev/shm is never captured.
// Also shredded on shutdown (see shutdown.ts). 0600, sourced by every shell via
// BASH_ENV + the image-baked /etc/profile.d + /etc/bash.bashrc hooks.
export const AGENT_ENV_DIR = '/dev/shm/kortix'
export const AGENT_ENV_SH = `${AGENT_ENV_DIR}/agent-env.sh`

const SECRET_NAME_RE = /^[A-Z_][A-Z0-9_]{0,63}$/
const NUL = String.fromCharCode(0)
const MAX_VALUE_BYTES = 128 * 1024

// Names that must NEVER be emitted into a sourced shell file regardless of how
// they got into the store — they hijack the loader, the shell, or the exec
// environment. This is the LAST line of defense; the API also filters these.
const DANGEROUS_NAMES = new Set([
  'PATH', 'HOME', 'PWD', 'USER', 'LOGNAME', 'SHELL', 'HOSTNAME', 'TERM', 'TMPDIR',
  'NODE_OPTIONS', 'LD_PRELOAD', 'LD_LIBRARY_PATH', 'LD_AUDIT', 'BASH_ENV', 'ENV',
  'IFS', 'PROMPT_COMMAND', 'PS1', 'PS2', 'PS3', 'PS4', 'SHELLOPTS', 'BASHOPTS',
  'GLOBIGNORE', 'CDPATH', 'HISTFILE',
])

function isUnsafeName(name: string): boolean {
  if (!SECRET_NAME_RE.test(name)) return true
  if (DANGEROUS_NAMES.has(name)) return true
  return (
    name.startsWith('KORTIX_') ||
    name.startsWith('OPENCODE_') ||
    name.startsWith('LD_') ||
    name.startsWith('DYLD_') ||
    name.startsWith('BASH_FUNC_')
  )
}

let writeSeq = 0

function atomicWrite(file: string, contents: string): boolean {
  try {
    mkdirSync(dirname(file), { recursive: true, mode: 0o700 })
    const tmp = `${file}.${process.pid}.${writeSeq++}.tmp`
    writeFileSync(tmp, contents, { encoding: 'utf8', mode: 0o600 })
    chmodSync(tmp, 0o600)
    renameSync(tmp, file)
    return true
  } catch (err) {
    logger.warn('[agent-env] failed to write live env file', {
      file,
      err: (err as Error).message,
    })
    return false
  }
}

function bootSecretNames(bootEnv: NodeJS.ProcessEnv): string[] {
  return (bootEnv.KORTIX_PROJECT_SECRET_NAMES ?? '')
    .split(',')
    .map((name) => name.trim())
    .filter(Boolean)
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

// Render `export NAME='value'` / `unset NAME` lines. Names are re-validated and
// dangerous/reserved names dropped (defense in depth — the daemon never trusts
// the API to have filtered). A NUL byte or oversized value is skipped rather
// than allowed to break `source` for every shell.
function renderShellEnv(env: Record<string, string>, bootNames: string[]): string {
  const lines = [
    '# Generated by kortix-sandbox-agent-server. Sourced by every sandbox shell',
    '# (BASH_ENV + /etc/profile.d). Do not edit.',
  ]
  for (const name of bootNames) {
    if (isUnsafeName(name)) continue
    if (!(name in env)) lines.push(`unset ${name}`)
  }
  for (const [name, value] of Object.entries(env)) {
    if (isUnsafeName(name)) {
      logger.warn('[agent-env] dropping reserved/unsafe secret name', { name })
      continue
    }
    if (value.includes(NUL)) {
      logger.warn('[agent-env] skipping secret with NUL byte in value', { name })
      continue
    }
    if (Buffer.byteLength(value, 'utf8') > MAX_VALUE_BYTES) {
      logger.warn('[agent-env] skipping oversized secret value', { name })
      continue
    }
    lines.push(`export ${name}=${shellQuote(value)}`)
  }
  return lines.join('\n') + '\n'
}

export function writeAgentEnvFile(
  store: ProjectEnvStore,
  opts: { sh?: string; bootEnv?: NodeJS.ProcessEnv } = {},
): boolean {
  const snapshot = store.snapshot()
  const bootNames = bootSecretNames(opts.bootEnv ?? process.env)
  return atomicWrite(opts.sh ?? AGENT_ENV_SH, renderShellEnv(snapshot.env, bootNames))
}

// Best-effort shred on shutdown: overwrite-in-place with random bytes then
// unlink the live file AND any orphaned atomicWrite temp files, so a
// hibernated/archived disk can't retain the plaintext even off the tmpfs path.
export function shredAgentEnvFile(file: string = AGENT_ENV_SH): void {
  const dir = dirname(file)
  let targets: string[] = [file]
  try {
    for (const name of readdirSync(dir)) {
      if (name.startsWith('agent-env.sh') && name.endsWith('.tmp')) targets.push(join(dir, name))
    }
  } catch {}
  for (const target of targets) {
    try {
      const size = Buffer.byteLength(readFileSync(target))
      if (size > 0) writeFileSync(target, randomBytes(size), { mode: 0o600 })
    } catch {}
    try {
      rmSync(target, { force: true })
    } catch {}
  }
}

// Verify /dev/shm is a real tmpfs mount. If it isn't, the secret file would be
// silently written to the persisted root fs — caller should surface this.
export function agentEnvDirIsTmpfs(): boolean {
  try {
    const mounts = readFileSync('/proc/mounts', 'utf8')
    return /\s\/dev\/shm\s+tmpfs\s/.test(mounts)
  } catch {
    return false
  }
}
