import { chmodSync, mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import { logger } from './logger'
import type { ProjectEnvStore } from './project-env'

export const AGENT_ENV_DIR = '/run/kortix'
export const AGENT_ENV_FILE = `${AGENT_ENV_DIR}/agent-env.json`
export const AGENT_ENV_SH = `${AGENT_ENV_DIR}/agent-env.sh`

let writeSeq = 0

function atomicWrite(file: string, contents: string): boolean {
  try {
    mkdirSync(dirname(file), { recursive: true, mode: 0o700 })
    const tmp = `${file}.${process.pid}.${writeSeq++}.tmp`
    writeFileSync(tmp, contents, { encoding: 'utf8', mode: 0o600 })
    chmodSync(tmp, 0o600)
    renameSync(tmp, file)
    return true
  } catch (err) {
    logger.warn('[agent-env] failed to write live env file', {
      file,
      err: (err as Error).message,
    })
    return false
  }
}

function bootSecretNames(bootEnv: NodeJS.ProcessEnv): string[] {
  return (bootEnv.KORTIX_PROJECT_SECRET_NAMES ?? '')
    .split(',')
    .map((name) => name.trim())
    .filter(Boolean)
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function renderShellEnv(env: Record<string, string>, bootNames: string[]): string {
  const lines = [
    '# Generated by kortix-sandbox-agent-server. Sourced by every sandbox shell',
    '# (BASH_ENV + /etc/profile.d). Do not edit.',
  ]
  for (const name of bootNames) {
    if (!(name in env)) lines.push(`unset ${name}`)
  }
  for (const [name, value] of Object.entries(env)) {
    lines.push(`export ${name}=${shellQuote(value)}`)
  }
  return lines.join('\n') + '\n'
}

export function writeAgentEnvFile(
  store: ProjectEnvStore,
  paths: { json?: string; sh?: string } = {},
  bootEnv: NodeJS.ProcessEnv = process.env,
): boolean {
  const snapshot = store.snapshot()
  const bootNames = bootSecretNames(bootEnv);
  const okJson = atomicWrite(
    paths.json ?? AGENT_ENV_FILE,
    JSON.stringify({ revision: snapshot.revision, names: snapshot.names, env: snapshot.env }),
  )
  const okSh = atomicWrite(paths.sh ?? AGENT_ENV_SH, renderShellEnv(snapshot.env, bootNames))
  return okJson && okSh
}
