'use client';

/**
 * name -> Phosphor component, for the 64 glyphs in the shared catalogue.
 *
 * The imports are EXPLICIT and one per glyph. `import * as Phosphor` would
 * resolve names dynamically and defeat tree-shaking, pulling all 1512 icons
 * (~5.3 MB of path data) into the bundle instead of the 64 we use (~224 KB).
 *
 * The catalogue in @kortix/shared is the source of truth for WHICH names exist;
 * this file is the source of truth for what each one DRAWS. glyph-registry.test
 * asserts the two agree in both directions, so a name added to one and not the
 * other fails CI rather than shipping a blank tile.
 */
import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  AsteriskIcon,
  AtIcon,
  BellIcon,
  BookIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BugIcon,
  CheckIcon,
  CircleIcon,
  ClipboardIcon,
  CloudIcon,
  CodeIcon,
  CopyIcon,
  CpuIcon,
  DatabaseIcon,
  DiamondIcon,
  DropIcon,
  FileIcon,
  FileTextIcon,
  FireIcon,
  FolderIcon,
  FolderOpenIcon,
  GiftIcon,
  GitBranchIcon,
  HammerIcon,
  HashIcon,
  HeartIcon,
  HexagonIcon,
  type Icon,
  InfoIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  MinusIcon,
  MoonIcon,
  MountainsIcon,
  NewspaperIcon,
  NoteIcon,
  PackageIcon,
  PaperclipIcon,
  PencilIcon,
  PercentIcon,
  PlanetIcon,
  PlusIcon,
  QuestionIcon,
  RocketIcon,
  ShoppingCartIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TerminalIcon,
  TrashIcon,
  TreeIcon,
  TrendDownIcon,
  TrendUpIcon,
  TriangleIcon,
  WarningIcon,
  WrenchIcon,
  XIcon,
} from '@phosphor-icons/react';

export const GLYPH_COMPONENTS: Record<string, Icon> = {
  // Objects
  Trash: TrashIcon,
  ShoppingCart: ShoppingCartIcon,
  Package: PackageIcon,
  Briefcase: BriefcaseIcon,
  Gift: GiftIcon,
  Lightbulb: LightbulbIcon,
  Wrench: WrenchIcon,
  Hammer: HammerIcon,
  // Shapes
  Circle: CircleIcon,
  Square: SquareIcon,
  Triangle: TriangleIcon,
  Diamond: DiamondIcon,
  Hexagon: HexagonIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  Lightning: LightningIcon,
  // Files
  File: FileIcon,
  FileText: FileTextIcon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  Note: NoteIcon,
  Book: BookIcon,
  Newspaper: NewspaperIcon,
  Paperclip: PaperclipIcon,
  // Actions
  Plus: PlusIcon,
  Minus: MinusIcon,
  Copy: CopyIcon,
  Clipboard: ClipboardIcon,
  Check: CheckIcon,
  X: XIcon,
  Pencil: PencilIcon,
  Bookmark: BookmarkIcon,
  // Arrows
  ArrowUp: ArrowUpIcon,
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowsClockwise: ArrowsClockwiseIcon,
  ArrowSquareOut: ArrowSquareOutIcon,
  TrendUp: TrendUpIcon,
  TrendDown: TrendDownIcon,
  // Tech
  Code: CodeIcon,
  Terminal: TerminalIcon,
  Database: DatabaseIcon,
  Cloud: CloudIcon,
  Cpu: CpuIcon,
  Bug: BugIcon,
  GitBranch: GitBranchIcon,
  Rocket: RocketIcon,
  // Nature
  Leaf: LeafIcon,
  Tree: TreeIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Drop: DropIcon,
  Fire: FireIcon,
  Mountains: MountainsIcon,
  Planet: PlanetIcon,
  // Symbols
  Hash: HashIcon,
  At: AtIcon,
  Percent: PercentIcon,
  Asterisk: AsteriskIcon,
  Question: QuestionIcon,
  Warning: WarningIcon,
  Info: InfoIcon,
  Bell: BellIcon,
};

export function glyphComponent(name: string): Icon | null {
  return GLYPH_COMPONENTS[name] ?? null;
}

/**
 * Search terms per glyph. Always includes the name lowercased, plus the words a
 * user would actually type — 'bin' and 'delete' for Trash, 'buy' and 'basket'
 * for ShoppingCart. Without these, search matches only the Phosphor identifier,
 * which is not a word most people would guess.
 */
export const GLYPH_SEARCH: Record<string, string[]> = {
  Trash: ['trash', 'bin', 'delete', 'remove'],
  ShoppingCart: ['shoppingcart', 'cart', 'buy', 'basket', 'shop', 'store'],
  Package: ['package', 'box', 'parcel', 'ship', 'delivery'],
  Briefcase: ['briefcase', 'work', 'business', 'job', 'case'],
  Gift: ['gift', 'present', 'reward', 'box'],
  Lightbulb: ['lightbulb', 'idea', 'bulb', 'light', 'tip'],
  Wrench: ['wrench', 'tool', 'fix', 'settings', 'repair'],
  Hammer: ['hammer', 'tool', 'build', 'construct'],
  Circle: ['circle', 'round', 'dot', 'shape'],
  Square: ['square', 'box', 'shape'],
  Triangle: ['triangle', 'shape'],
  Diamond: ['diamond', 'gem', 'shape', 'rhombus'],
  Hexagon: ['hexagon', 'shape', 'hex'],
  Star: ['star', 'favourite', 'favorite', 'rating'],
  Heart: ['heart', 'love', 'like', 'favourite', 'favorite'],
  Lightning: ['lightning', 'bolt', 'fast', 'power', 'energy', 'zap'],
  File: ['file', 'document', 'page'],
  FileText: ['filetext', 'document', 'text', 'doc', 'page'],
  Folder: ['folder', 'directory'],
  FolderOpen: ['folderopen', 'directory', 'open'],
  Note: ['note', 'memo', 'sticky'],
  Book: ['book', 'read', 'docs', 'manual', 'library'],
  Newspaper: ['newspaper', 'news', 'article', 'press'],
  Paperclip: ['paperclip', 'attach', 'attachment', 'clip'],
  Plus: ['plus', 'add', 'new', 'create'],
  Minus: ['minus', 'remove', 'subtract', 'less'],
  Copy: ['copy', 'duplicate', 'clone'],
  Clipboard: ['clipboard', 'paste', 'copy'],
  Check: ['check', 'done', 'tick', 'complete', 'ok'],
  X: ['x', 'close', 'cancel', 'cross', 'remove'],
  Pencil: ['pencil', 'edit', 'write', 'draw'],
  Bookmark: ['bookmark', 'save', 'mark', 'flag'],
  ArrowUp: ['arrowup', 'up', 'north', 'increase'],
  ArrowDown: ['arrowdown', 'down', 'south', 'decrease'],
  ArrowLeft: ['arrowleft', 'left', 'back', 'west'],
  ArrowRight: ['arrowright', 'right', 'forward', 'next', 'east'],
  ArrowsClockwise: ['arrowsclockwise', 'refresh', 'reload', 'sync', 'retry'],
  ArrowSquareOut: ['arrowsquareout', 'external', 'open', 'link', 'launch'],
  TrendUp: ['trendup', 'growth', 'increase', 'chart', 'up'],
  TrendDown: ['trenddown', 'decline', 'decrease', 'chart', 'down'],
  Code: ['code', 'develop', 'program', 'source'],
  Terminal: ['terminal', 'console', 'shell', 'cli', 'command'],
  Database: ['database', 'db', 'storage', 'data', 'sql'],
  Cloud: ['cloud', 'server', 'hosting', 'sky'],
  Cpu: ['cpu', 'chip', 'processor', 'compute', 'hardware'],
  Bug: ['bug', 'issue', 'defect', 'error', 'debug'],
  GitBranch: ['gitbranch', 'git', 'branch', 'repo', 'version'],
  Rocket: ['rocket', 'launch', 'ship', 'deploy', 'space'],
  Leaf: ['leaf', 'nature', 'plant', 'eco', 'green'],
  Tree: ['tree', 'nature', 'forest', 'plant'],
  Sun: ['sun', 'day', 'light', 'weather', 'bright'],
  Moon: ['moon', 'night', 'dark', 'sleep'],
  Drop: ['drop', 'water', 'liquid', 'rain'],
  Fire: ['fire', 'flame', 'hot', 'burn', 'trending'],
  Mountains: ['mountains', 'mountain', 'peak', 'nature', 'hike'],
  Planet: ['planet', 'space', 'world', 'globe', 'orbit'],
  Hash: ['hash', 'number', 'tag', 'channel', 'pound'],
  At: ['at', 'mention', 'email', 'address'],
  Percent: ['percent', 'percentage', 'discount', 'rate'],
  Asterisk: ['asterisk', 'star', 'required', 'wildcard'],
  Question: ['question', 'help', 'ask', 'faq', 'unknown'],
  Warning: ['warning', 'alert', 'caution', 'danger'],
  Info: ['info', 'information', 'about', 'details'],
  Bell: ['bell', 'notification', 'alert', 'reminder'],
};
