/**
 * Build-time only: derives each catalogue glyph's path in the app's icon
 * weight from its Phosphor component. Imported by
 * `scripts/generate-glyph-paths.tsx` and by glyph-face.test.tsx (the drift
 * guard), never by application code — it pulls in the full registry and
 * react-dom/server.
 */
import { IconContext } from '@phosphor-icons/react';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

import { GLYPH_COMPONENTS } from '@/components/ui/glyph-registry';
import { DEFAULT_ICON_WEIGHT } from '@/lib/icons/icon-config';

export function glyphPathsInDefaultWeight(): Record<string, string> {
  const paths: Record<string, string> = {};
  for (const name of Object.keys(GLYPH_COMPONENTS).sort()) {
    const html = renderToStaticMarkup(
      createElement(
        IconContext.Provider,
        { value: { weight: DEFAULT_ICON_WEIGHT } },
        createElement(GLYPH_COMPONENTS[name]!),
      ),
    );
    const inner = html.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
    const match = inner.match(/^<path d="([^"]+)"><\/path>$/);
    if (!match) {
      throw new Error(`glyph ${name} is not one <path> in weight ${DEFAULT_ICON_WEIGHT}: ${inner.slice(0, 80)}`);
    }
    paths[name] = match[1]!;
  }
  return paths;
}

export function renderGlyphPathsModule(): string {
  const paths = glyphPathsInDefaultWeight();
  const lines = Object.entries(paths).map(([name, d]) => `  ${JSON.stringify(name)}: ${JSON.stringify(d)},`);
  return [
    '// GENERATED by apps/web/scripts/generate-glyph-paths.tsx. Do not edit.',
    '// The path of every catalogue glyph in DEFAULT_ICON_WEIGHT; see glyph-face.tsx.',
    '',
    `export const GLYPH_PATHS_WEIGHT = ${JSON.stringify(DEFAULT_ICON_WEIGHT)};`,
    '',
    'export const GLYPH_PATHS: Readonly<Record<string, string>> = {',
    ...lines,
    '};',
    '',
  ].join('\n');
}
