/**
 * Kortix Suna - Comprehensive Convex Schema
 *
 * This schema merges:
 * 1. Cortex Memory SDK tables (Layer 1-4 + Coordination)
 * 2. Application tables (migrated from Supabase)
 * 3. Better Auth tables (reference - auto-generated by better-auth-convex)
 *
 * Naming Convention: camelCase for all fields (Convex standard)
 * Timestamps: Unix epoch milliseconds (v.number())
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ═══════════════════════════════════════════════════════════════════════════════
  // CORTEX MEMORY SDK TABLES (Layer 1-4 + Coordination)
  // ═══════════════════════════════════════════════════════════════════════════════

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Layer 1a: Conversations (ACID, Immutable)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  conversations: defineTable({
    // Identity
    conversationId: v.string(), // Unique ID (e.g., "conv-abc123")

    // Memory Space (fundamental isolation boundary)
    memorySpaceId: v.string(), // Which memory space owns this conversation
    participantId: v.optional(v.string()), // Hive Mode: which participant created this

    // Type: user-agent (user ↔ participant) or agent-agent (space ↔ space)
    type: v.union(v.literal("user-agent"), v.literal("agent-agent")),

    // Participants (based on type)
    participants: v.object({
      // user-agent conversations
      userId: v.optional(v.string()), // The human user in the conversation
      agentId: v.optional(v.string()), // The agent/assistant in the conversation

      // Hive Mode tracking (which tool/agent in shared space created this)
      participantId: v.optional(v.string()),

      // agent-agent conversations (Collaboration Mode - cross-space)
      memorySpaceIds: v.optional(v.array(v.string())), // Both spaces involved
    }),

    // Messages (append-only, immutable)
    messages: v.array(
      v.object({
        id: v.string(), // Message ID
        role: v.union(
          v.literal("user"),
          v.literal("agent"),
          v.literal("system"),
        ),
        content: v.string(),
        timestamp: v.number(),

        // Optional fields
        participantId: v.optional(v.string()), // Which participant sent this (Hive Mode)
        metadata: v.optional(v.any()), // Flexible metadata
      }),
    ),

    // Statistics
    messageCount: v.number(),

    // Metadata (flexible)
    metadata: v.optional(v.any()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_conversationId", ["conversationId"]) // Unique lookup
    .index("by_memorySpace", ["memorySpaceId"]) // Memory space's conversations
    .index("by_type", ["type"]) // List by type
    .index("by_user", ["participants.userId"]) // User's conversations
    .index("by_agent", ["participants.agentId"]) // Agent's conversations
    .index("by_memorySpace_user", ["memorySpaceId", "participants.userId"]) // Space + user
    .index("by_memorySpace_agent", ["memorySpaceId", "participants.agentId"]) // Space + agent
    .index("by_created", ["createdAt"]), // Chronological ordering

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Layer 1b: Immutable Store (ACID, Versioned, Shared)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  immutable: defineTable({
    // Identity (composite key: type + id)
    type: v.string(), // Entity type: 'kb-article', 'policy', 'audit-log', 'feedback', 'user'
    id: v.string(), // Type-specific logical ID

    // Data (flexible, immutable once stored)
    data: v.any(),

    // GDPR support (optional)
    userId: v.optional(v.string()), // Links to user for cascade deletion

    // Versioning
    version: v.number(), // Current version number (starts at 1)
    previousVersions: v.array(
      v.object({
        version: v.number(),
        data: v.any(),
        timestamp: v.number(),
        metadata: v.optional(v.any()),
      }),
    ),

    // Metadata (flexible)
    metadata: v.optional(
      v.object({
        publishedBy: v.optional(v.string()),
        tags: v.optional(v.array(v.string())),
        importance: v.optional(v.number()),
      }),
    ),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_type_id", ["type", "id"]) // Unique lookup
    .index("by_type", ["type"]) // List by type
    .index("by_userId", ["userId"]) // GDPR cascade
    .index("by_created", ["createdAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Layer 1c: Mutable Store (ACID, No Versioning, Shared)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  mutable: defineTable({
    // Composite key: namespace + key
    namespace: v.string(), // Logical grouping: 'inventory', 'config', 'counters', etc.
    key: v.string(), // Unique key within namespace

    // Value (flexible, mutable)
    value: v.any(),

    // GDPR support (optional)
    userId: v.optional(v.string()), // Links to user for cascade deletion

    // Metadata (optional)
    metadata: v.optional(v.any()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),

    // Access tracking
    accessCount: v.number(),
    lastAccessed: v.optional(v.number()),
  })
    .index("by_namespace_key", ["namespace", "key"]) // Unique lookup
    .index("by_namespace", ["namespace"]) // List by namespace
    .index("by_userId", ["userId"]) // GDPR cascade
    .index("by_updated", ["updatedAt"]), // Recent changes

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Layer 2: Vector Memory (Searchable, memorySpace-scoped, Versioned)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  memories: defineTable({
    // Identity
    memoryId: v.string(), // Unique ID for this memory
    memorySpaceId: v.string(), // Memory space isolation (was agentId)
    participantId: v.optional(v.string()), // Hive Mode participant tracking

    // Content
    content: v.string(),
    contentType: v.union(
      v.literal("raw"),
      v.literal("summarized"),
      v.literal("fact"), // For facts indexed in vector layer
    ),
    embedding: v.optional(v.array(v.float64())), // Optional for keyword-only

    // Source (flattened for indexing performance)
    sourceType: v.union(
      v.literal("conversation"),
      v.literal("system"),
      v.literal("tool"),
      v.literal("a2a"),
      v.literal("fact-extraction"), // For facts
    ),
    sourceUserId: v.optional(v.string()),
    sourceUserName: v.optional(v.string()),
    sourceTimestamp: v.number(),

    // Message role (for conversation memories) - helps with semantic search weighting
    messageRole: v.optional(
      v.union(v.literal("user"), v.literal("agent"), v.literal("system")),
    ),

    // Owner Attribution (at least one required for proper tracking)
    userId: v.optional(v.string()), // For user-owned memories (GDPR cascade)
    agentId: v.optional(v.string()), // For agent-owned memories (agent deletion cascade)

    // References to Layer 1 (mutually exclusive, all optional)
    conversationRef: v.optional(
      v.object({
        conversationId: v.string(),
        messageIds: v.array(v.string()),
      }),
    ),

    immutableRef: v.optional(
      v.object({
        type: v.string(),
        id: v.string(),
        version: v.optional(v.number()),
      }),
    ),

    mutableRef: v.optional(
      v.object({
        namespace: v.string(),
        key: v.string(),
        snapshotValue: v.any(),
        snapshotAt: v.number(),
      }),
    ),

    // Reference to Layer 3 fact
    factsRef: v.optional(
      v.object({
        factId: v.string(),
        version: v.optional(v.number()),
      }),
    ),

    // Metadata (flattened for indexing/filtering)
    importance: v.number(), // 0-100 (flattened for filtering)
    tags: v.array(v.string()), // Flattened for filtering

    // Enrichment Fields (for bullet-proof retrieval)
    enrichedContent: v.optional(v.string()), // Concatenated searchable content for embedding
    factCategory: v.optional(v.string()), // Category for filtering (e.g., "addressing_preference")

    // Flexible metadata (for source-specific data like A2A direction, messageId, etc.)
    metadata: v.optional(v.any()),

    // Versioning (like immutable)
    version: v.number(),
    previousVersions: v.array(
      v.object({
        version: v.number(),
        content: v.string(),
        embedding: v.optional(v.array(v.float64())),
        timestamp: v.number(),
      }),
    ),

    // Timestamps & Access
    createdAt: v.number(),
    updatedAt: v.number(),
    lastAccessed: v.optional(v.number()),
    accessCount: v.number(),

    // Streaming support (for progressive storage)
    isPartial: v.optional(v.boolean()), // Flag for in-progress streaming memories
    partialMetadata: v.optional(v.any()), // Metadata for partial/streaming memories
  })
    .index("by_memorySpace", ["memorySpaceId"]) // Memory space's memories
    .index("by_memoryId", ["memoryId"]) // Unique lookup
    .index("by_userId", ["userId"]) // GDPR cascade
    .index("by_agentId", ["agentId"]) // Agent deletion cascade
    .index("by_memorySpace_created", ["memorySpaceId", "createdAt"]) // Chronological
    .index("by_memorySpace_userId", ["memorySpaceId", "userId"]) // Space + user
    .index("by_memorySpace_agentId", ["memorySpaceId", "agentId"]) // Space + agent
    .index("by_participantId", ["participantId"]) // Hive Mode tracking
    .searchIndex("by_content", {
      searchField: "content",
      filterFields: [
        "memorySpaceId",
        "sourceType",
        "userId",
        "agentId",
        "participantId",
      ],
    })
    .vectorIndex("by_embedding", {
      vectorField: "embedding",
      dimensions: 1536, // Default: OpenAI text-embedding-3-small
      filterFields: ["memorySpaceId", "userId", "agentId", "participantId"],
    }),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Layer 3: Facts Store (memorySpace-scoped, Versioned)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  facts: defineTable({
    // Identity
    factId: v.string(), // Unique ID for this fact
    memorySpaceId: v.string(), // Memory space isolation
    participantId: v.optional(v.string()), // Hive Mode: which participant extracted this
    userId: v.optional(v.string()), // GDPR compliance - links to user

    // Fact content
    fact: v.string(), // The fact statement
    factType: v.union(
      v.literal("preference"),
      v.literal("identity"),
      v.literal("knowledge"),
      v.literal("relationship"),
      v.literal("event"),
      v.literal("observation"),
      v.literal("custom"),
    ),

    // Triple structure (subject-predicate-object)
    subject: v.optional(v.string()), // Primary entity (e.g., "user-123")
    predicate: v.optional(v.string()), // Relationship (e.g., "prefers", "works_at")
    object: v.optional(v.string()), // Secondary entity (e.g., "dark mode")

    // Quality & Source
    confidence: v.number(), // 0-100: extraction confidence
    sourceType: v.union(
      v.literal("conversation"),
      v.literal("system"),
      v.literal("tool"),
      v.literal("manual"),
      v.literal("a2a"),
    ),
    sourceRef: v.optional(
      v.object({
        conversationId: v.optional(v.string()),
        messageIds: v.optional(v.array(v.string())),
        memoryId: v.optional(v.string()),
      }),
    ),

    // Metadata & Tags
    metadata: v.optional(v.any()),
    tags: v.array(v.string()),

    // Enrichment Fields (for bullet-proof retrieval)
    category: v.optional(v.string()), // Specific sub-category (e.g., "addressing_preference")
    searchAliases: v.optional(v.array(v.string())), // Alternative search terms
    semanticContext: v.optional(v.string()), // Usage context sentence
    entities: v.optional(
      v.array(
        v.object({
          name: v.string(),
          type: v.string(),
          fullValue: v.optional(v.string()),
        }),
      ),
    ), // Extracted entities with types
    relations: v.optional(
      v.array(
        v.object({
          subject: v.string(),
          predicate: v.string(),
          object: v.string(),
        }),
      ),
    ), // Subject-predicate-object triples for graph

    // Temporal validity
    validFrom: v.optional(v.number()),
    validUntil: v.optional(v.number()),

    // Versioning (creates immutable chain)
    version: v.number(),
    supersededBy: v.optional(v.string()), // factId of newer version
    supersedes: v.optional(v.string()), // factId this replaces

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_factId", ["factId"]) // Unique lookup
    .index("by_memorySpace", ["memorySpaceId"]) // Memory space's facts
    .index("by_memorySpace_subject", ["memorySpaceId", "subject"]) // Entity-centric queries
    .index("by_participantId", ["participantId"]) // Hive Mode tracking
    .index("by_userId", ["userId"]) // GDPR cascade
    .searchIndex("by_content", {
      searchField: "fact",
      filterFields: ["memorySpaceId", "factType"],
    }),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Memory Spaces Registry (Hive/Collaboration Mode Management)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  memorySpaces: defineTable({
    // Identity
    memorySpaceId: v.string(), // Unique memory space ID
    name: v.optional(v.string()), // Human-readable name
    type: v.union(
      v.literal("personal"),
      v.literal("team"),
      v.literal("project"),
      v.literal("custom"),
    ),

    // Participants (for Hive Mode)
    participants: v.array(
      v.object({
        id: v.string(), // Participant ID (e.g., 'cursor', 'claude', 'my-bot')
        type: v.string(), // 'ai-tool', 'human', 'ai-agent', 'system'
        joinedAt: v.number(),
      }),
    ),

    // Metadata (flexible)
    metadata: v.any(),

    // Status
    status: v.union(v.literal("active"), v.literal("archived")),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_memorySpaceId", ["memorySpaceId"]) // Unique lookup
    .index("by_status", ["status"]) // Filter active/archived
    .index("by_type", ["type"]) // Filter by type
    .index("by_created", ["createdAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Contexts (Hierarchical Coordination, memorySpace-scoped with cross-space support)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  contexts: defineTable({
    // Identity
    contextId: v.string(), // Unique ID
    memorySpaceId: v.string(), // Which memory space owns this context

    // Purpose
    purpose: v.string(), // What this context is for

    // Hierarchy
    parentId: v.optional(v.string()), // Parent context (can be cross-space)
    rootId: v.optional(v.string()), // Root context
    depth: v.number(), // 0 for root, increments with depth
    childIds: v.array(v.string()), // Child contexts

    // Status
    status: v.union(
      v.literal("active"),
      v.literal("completed"),
      v.literal("cancelled"),
      v.literal("blocked"),
    ),

    // Source conversation (optional)
    conversationRef: v.optional(
      v.object({
        conversationId: v.string(),
        messageIds: v.optional(v.array(v.string())),
      }),
    ),

    // User association (GDPR)
    userId: v.optional(v.string()),

    // Participants (for tracking)
    participants: v.array(v.string()), // Memory spaces or participants involved

    // Cross-space access control
    grantedAccess: v.optional(
      v.array(
        v.object({
          memorySpaceId: v.string(), // Which space has access
          scope: v.string(), // 'read-only', 'context-only', etc.
          grantedAt: v.number(),
        }),
      ),
    ),

    // Data (flexible)
    data: v.optional(v.any()),

    // Metadata
    metadata: v.optional(v.any()),

    // Versioning (automatic version tracking for updates)
    version: v.number(), // Current version number (starts at 1)
    previousVersions: v.array(
      v.object({
        version: v.number(),
        status: v.string(),
        data: v.optional(v.any()),
        timestamp: v.number(),
        updatedBy: v.optional(v.string()), // Agent/participant that made the change
      }),
    ),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_contextId", ["contextId"]) // Unique lookup
    .index("by_memorySpace", ["memorySpaceId"]) // Space's contexts
    .index("by_parentId", ["parentId"]) // Child lookup
    .index("by_rootId", ["rootId"]) // All contexts in tree
    .index("by_status", ["status"]) // Filter by status
    .index("by_memorySpace_status", ["memorySpaceId", "status"])
    .index("by_userId", ["userId"]) // GDPR cascade
    .index("by_created", ["createdAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // SDK Agents Registry (Optional Metadata Layer for SDK)
  // NOTE: This is for Cortex SDK internal agent tracking
  // Application agents are stored in 'appAgents' table below
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  agents: defineTable({
    // Identity
    agentId: v.string(), // Unique agent identifier

    // Metadata
    name: v.string(), // Display name
    description: v.optional(v.string()), // What this agent does
    metadata: v.optional(v.any()), // Flexible metadata (team, capabilities, etc.)

    // Configuration
    config: v.optional(v.any()), // Agent-specific configuration

    // Status
    status: v.union(
      v.literal("active"),
      v.literal("inactive"),
      v.literal("archived"),
    ),

    // Timestamps
    registeredAt: v.number(),
    updatedAt: v.number(),
    lastActive: v.optional(v.number()), // Last time agent created data
  })
    .index("by_agentId", ["agentId"]) // Unique lookup
    .index("by_status", ["status"]) // Filter by status
    .index("by_registered", ["registeredAt"]), // Chronological ordering

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Governance Policies (Data Retention, Purging, and Compliance)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  governancePolicies: defineTable({
    // Scope
    organizationId: v.optional(v.string()),
    memorySpaceId: v.optional(v.string()), // Memory space override

    // Policy configuration (full JSON structure)
    policy: v.any(), // GovernancePolicy structure

    // Metadata
    isActive: v.boolean(),
    appliedBy: v.optional(v.string()), // Who applied this policy

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organization", ["organizationId"])
    .index("by_memorySpace", ["memorySpaceId"])
    .index("by_active", ["isActive", "organizationId"])
    .index("by_updated", ["updatedAt"]),

  // Governance Enforcement Log (Audit Trail)
  governanceEnforcement: defineTable({
    // Scope
    organizationId: v.optional(v.string()),
    memorySpaceId: v.optional(v.string()),

    // Enforcement details
    enforcementType: v.union(v.literal("automatic"), v.literal("manual")),
    layers: v.array(v.string()), // Which layers were enforced
    rules: v.array(v.string()), // Which rules were enforced

    // Results
    versionsDeleted: v.number(),
    recordsPurged: v.number(),
    storageFreed: v.number(), // MB

    // Metadata
    triggeredBy: v.optional(v.string()),

    // Timestamps
    executedAt: v.number(),
  })
    .index("by_organization", ["organizationId", "executedAt"])
    .index("by_memorySpace", ["memorySpaceId", "executedAt"])
    .index("by_executed", ["executedAt"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Graph Sync Queue (Real-time Graph Database Synchronization)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  graphSyncQueue: defineTable({
    // Entity identification
    table: v.string(), // "memories", "facts", "contexts", "conversations", etc.
    entityId: v.string(), // Cortex entity ID

    // Operation type
    operation: v.union(
      v.literal("insert"),
      v.literal("update"),
      v.literal("delete"),
    ),

    // Entity data (full object for sync)
    entity: v.optional(v.any()), // Null for deletes

    // Sync status
    synced: v.boolean(),
    syncedAt: v.optional(v.number()),

    // Retry tracking
    failedAttempts: v.optional(v.number()),
    lastError: v.optional(v.string()),

    // Priority (for ordering)
    priority: v.optional(v.string()), // "high", "normal", "low"

    // Timestamps
    createdAt: v.number(),
  })
    .index("by_synced", ["synced"]) // Get unsynced items (reactive query!)
    .index("by_table", ["table"]) // Filter by entity type
    .index("by_table_entity", ["table", "entityId"]) // Unique lookup
    .index("by_priority", ["priority", "synced"]) // Priority-based processing
    .index("by_created", ["createdAt"]), // Chronological

  // ═══════════════════════════════════════════════════════════════════════════════
  // APPLICATION TABLES (Migrated from Supabase)
  // ═══════════════════════════════════════════════════════════════════════════════

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Projects - User/Account projects for organizing threads
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  projects: defineTable({
    // Identity
    projectId: v.string(), // Unique project ID (was UUID)

    // Ownership
    accountId: v.string(), // Reference to Basejump/Better Auth account

    // Content
    name: v.string(),
    description: v.optional(v.string()),

    // Configuration
    sandbox: v.optional(v.any()), // Sandbox configuration (JSON)
    isPublic: v.boolean(), // Public visibility flag

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_projectId", ["projectId"]) // Unique lookup
    .index("by_account", ["accountId"]) // Account's projects
    .index("by_account_created", ["accountId", "createdAt"]) // Chronological by account
    .index("by_public", ["isPublic"]) // Filter public projects
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // App Agents - User-configured AI agents (renamed from 'agents' to avoid SDK conflict)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  appAgents: defineTable({
    // Identity
    agentId: v.string(), // Unique agent ID (was UUID)

    // Ownership
    accountId: v.string(), // Reference to Basejump/Better Auth account

    // Content
    name: v.string(),
    description: v.optional(v.string()),
    systemPrompt: v.optional(v.string()), // Made nullable per migration

    // Configuration
    configuredMcps: v.optional(v.any()), // MCP server configurations (JSON array)
    customMcps: v.optional(v.any()), // Custom MCP configurations (JSON array)
    agentpressTools: v.optional(v.any()), // Tool configurations (JSON object)

    // Default agent tracking
    isDefault: v.boolean(), // Is this the account's default agent?

    // Visual identity
    avatar: v.optional(v.string()), // Emoji avatar
    avatarColor: v.optional(v.string()), // Hex color for avatar background
    iconName: v.optional(v.string()), // Lucide icon name for avatar

    // Metadata (flexible - stores isSunaDefault, centrallyManaged, restrictions, etc.)
    metadata: v.optional(v.any()),

    // Marketplace/public fields
    isPublic: v.optional(v.boolean()), // Published to marketplace
    marketplacePublishedAt: v.optional(v.number()), // When published
    downloadCount: v.optional(v.number()), // Download count for marketplace

    // Tagging
    tags: v.optional(v.array(v.string())), // Tags for categorization

    // Version tracking
    currentVersionId: v.optional(v.string()), // Current version ID
    versionCount: v.optional(v.number()), // Number of versions

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_agentId", ["agentId"]) // Unique lookup
    .index("by_account", ["accountId"]) // Account's agents
    .index("by_account_created", ["accountId", "createdAt"]) // Chronological by account
    .index("by_default", ["accountId", "isDefault"]) // Find default agent per account
    .index("by_public", ["isPublic"]) // Marketplace agents
    .index("by_created", ["createdAt"]) // Global chronological
    .searchIndex("by_name", {
      searchField: "name",
      filterFields: ["accountId", "isPublic"],
    }),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Threads - Conversation threads
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  threads: defineTable({
    // Identity
    threadId: v.string(), // Unique thread ID (was UUID)

    // Ownership
    accountId: v.string(), // Reference to Basejump/Better Auth account

    // Project association
    projectId: v.optional(v.string()), // Optional project reference

    // Agent association (optional - agent-agnostic threads supported)
    agentId: v.optional(v.string()), // Default agent for this thread

    // Visibility
    isPublic: v.boolean(), // Public visibility flag

    // Flexible metadata (stores agentBuilderMode, targetAgent, etc.)
    metadata: v.optional(v.any()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_threadId", ["threadId"]) // Unique lookup
    .index("by_account", ["accountId"]) // Account's threads
    .index("by_project", ["projectId"]) // Project's threads
    .index("by_agent", ["agentId"]) // Agent's threads
    .index("by_account_created", ["accountId", "createdAt"]) // Chronological by account
    .index("by_project_created", ["projectId", "createdAt"]) // Chronological by project
    .index("by_public", ["isPublic"]) // Filter public threads
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Messages - Individual messages within threads
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  messages: defineTable({
    // Identity
    messageId: v.string(), // Unique message ID (was UUID)

    // Thread association
    threadId: v.string(), // Parent thread

    // Content
    type: v.string(), // Message type (e.g., "text", "tool_call", "summary")
    isLlmMessage: v.boolean(), // Is this an LLM-formatted message?
    content: v.any(), // Message content (JSON - flexible structure)

    // Agent association (for per-message agent selection)
    agentId: v.optional(v.string()), // Agent that generated/should respond to this message

    // Flexible metadata
    metadata: v.optional(v.any()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_messageId", ["messageId"]) // Unique lookup
    .index("by_thread", ["threadId"]) // Thread's messages
    .index("by_thread_created", ["threadId", "createdAt"]) // Chronological in thread
    .index("by_agent", ["agentId"]) // Messages by agent
    .index("by_type", ["type"]) // Filter by message type
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Agent Runs - Execution records for agent runs on threads
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  agentRuns: defineTable({
    // Identity
    runId: v.string(), // Unique run ID (was UUID)

    // Thread association
    threadId: v.string(), // Parent thread

    // Execution state
    status: v.string(), // 'running', 'completed', 'failed', 'queued'

    // Timing
    startedAt: v.number(), // When run started
    completedAt: v.optional(v.number()), // When run completed

    // Error handling
    error: v.optional(v.string()), // Error message if failed

    // Configuration metadata (model, streaming params, etc.)
    metadata: v.optional(v.any()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_runId", ["runId"]) // Unique lookup
    .index("by_thread", ["threadId"]) // Thread's runs
    .index("by_thread_created", ["threadId", "createdAt"]) // Chronological in thread
    .index("by_status", ["status"]) // Filter by status
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Agent Triggers - Automated trigger configurations for agents
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  agentTriggers: defineTable({
    // Identity
    triggerId: v.string(), // Unique trigger ID (was UUID)

    // Agent association
    agentId: v.string(), // Parent agent

    // Trigger configuration
    triggerType: v.string(), // 'telegram', 'slack', 'webhook', 'schedule', 'email', 'github', 'discord', 'teams'
    name: v.string(), // Human-readable name
    description: v.optional(v.string()),

    // State
    isActive: v.boolean(), // Is trigger enabled?

    // Configuration (provider-specific)
    config: v.optional(v.any()), // JSON configuration

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_triggerId", ["triggerId"]) // Unique lookup
    .index("by_agent", ["agentId"]) // Agent's triggers
    .index("by_type", ["triggerType"]) // Filter by trigger type
    .index("by_active", ["isActive"]) // Filter active triggers
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Trigger Events - Audit log for trigger executions
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  triggerEvents: defineTable({
    // Identity
    eventId: v.string(), // Unique event ID (was UUID)

    // Associations
    triggerId: v.string(), // Parent trigger
    agentId: v.string(), // Agent that was triggered

    // Execution result
    success: v.boolean(), // Did trigger succeed?
    shouldExecuteAgent: v.optional(v.boolean()), // Should agent be executed?

    // Error handling
    errorMessage: v.optional(v.string()),

    // Flexible metadata (event data, processing results)
    metadata: v.optional(v.any()),

    // Timestamp
    timestamp: v.number(),
  })
    .index("by_eventId", ["eventId"]) // Unique lookup
    .index("by_trigger", ["triggerId"]) // Trigger's events
    .index("by_agent", ["agentId"]) // Agent's trigger events
    .index("by_timestamp", ["timestamp"]) // Chronological
    .index("by_trigger_timestamp", ["triggerId", "timestamp"]) // Per-trigger chronological
    .index("by_success", ["success"]), // Filter by success

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // OAuth Installations - OAuth integration data for triggers
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  oauthInstallations: defineTable({
    // Identity
    installationId: v.string(), // Unique installation ID (was UUID)

    // Trigger association
    triggerId: v.string(), // Parent trigger

    // Provider info
    provider: v.string(), // 'slack', 'discord', 'teams', etc.

    // OAuth tokens
    accessToken: v.string(), // OAuth access token (encrypted at rest)
    refreshToken: v.optional(v.string()), // OAuth refresh token
    expiresIn: v.optional(v.number()), // Token expiration in seconds
    scope: v.optional(v.string()), // Granted scopes

    // Provider-specific data (workspace info, bot details, etc.)
    providerData: v.optional(v.any()),

    // Timestamps
    installedAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_installationId", ["installationId"]) // Unique lookup
    .index("by_trigger", ["triggerId"]) // Trigger's installations
    .index("by_provider", ["provider"]) // Filter by provider
    .index("by_installed", ["installedAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Custom Trigger Providers - Dynamic trigger provider definitions
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  customTriggerProviders: defineTable({
    // Identity
    providerId: v.string(), // Unique provider ID (was VARCHAR PK)

    // Content
    name: v.string(), // Display name
    description: v.string(), // Provider description

    // Configuration
    triggerType: v.string(), // Type of trigger this provider handles
    providerClass: v.optional(v.string()), // Full import path for custom providers
    configSchema: v.optional(v.any()), // JSON schema for configuration

    // Webhook support
    webhookEnabled: v.optional(v.boolean()),
    webhookConfig: v.optional(v.any()),

    // Response handling
    responseTemplate: v.optional(v.any()),
    fieldMappings: v.optional(v.any()), // Maps webhook fields to execution variables

    // State
    isActive: v.boolean(), // Is provider enabled?

    // Ownership
    createdBy: v.optional(v.string()), // Account ID of creator

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_providerId", ["providerId"]) // Unique lookup
    .index("by_type", ["triggerType"]) // Filter by trigger type
    .index("by_active", ["isActive"]) // Filter active providers
    .index("by_creator", ["createdBy"]) // Provider by creator
    .index("by_created", ["createdAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Credit Accounts - User credit balances
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  creditAccounts: defineTable({
    // Identity (userId is the primary key)
    userId: v.string(), // User ID (references Better Auth user)

    // Balance tracking
    balance: v.number(), // Current balance (decimal stored as float64)

    // Lifetime tracking
    lifetimeGranted: v.number(), // Total credits granted
    lifetimePurchased: v.number(), // Total credits purchased
    lifetimeUsed: v.number(), // Total credits used

    // Grant tracking
    lastGrantAt: v.optional(v.number()), // Last time credits were granted

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_userId", ["userId"]) // Unique lookup
    .index("by_updated", ["updatedAt"]), // Recent updates

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Credit Ledger - Transaction history for credits
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  creditLedger: defineTable({
    // Identity
    transactionId: v.string(), // Unique transaction ID (was UUID)

    // User association
    userId: v.string(), // User ID

    // Transaction details
    amount: v.number(), // Credit amount (positive for add, negative for deduct)
    balanceAfter: v.number(), // Balance after this transaction

    // Transaction type
    type: v.string(), // 'tier_grant', 'purchase', 'admin_grant', 'promotional', 'usage', 'refund', 'adjustment', 'expired'

    // Description and reference
    description: v.optional(v.string()),
    referenceId: v.optional(v.string()), // Reference to related entity
    referenceType: v.optional(v.string()), // Type of referenced entity

    // Additional metadata
    metadata: v.optional(v.any()),
    createdBy: v.optional(v.string()), // Admin who created this (if applicable)

    // Timestamp
    createdAt: v.number(),
  })
    .index("by_transactionId", ["transactionId"]) // Unique lookup
    .index("by_user", ["userId"]) // User's transactions
    .index("by_user_created", ["userId", "createdAt"]) // Chronological per user
    .index("by_type", ["type"]) // Filter by type
    .index("by_reference", ["referenceId", "referenceType"]) // Lookup by reference
    .index("by_created", ["createdAt"]), // Global chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Credit Grants - Periodic credit grant records
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  creditGrants: defineTable({
    // Identity
    grantId: v.string(), // Unique grant ID (was UUID)

    // User association
    userId: v.string(), // User ID

    // Subscription association
    tierPriceId: v.optional(v.string()), // Stripe tier price ID

    // Grant details
    amount: v.number(), // Credits granted

    // Timing
    grantedAt: v.number(), // When granted
    expiresAt: v.optional(v.number()), // When credits expire

    // Billing period
    periodStart: v.number(), // Start of billing period
    periodEnd: v.number(), // End of billing period
  })
    .index("by_grantId", ["grantId"]) // Unique lookup
    .index("by_user", ["userId"]) // User's grants
    .index("by_user_period", ["userId", "periodStart", "periodEnd"]) // Grants in period
    .index("by_expires", ["expiresAt"]), // Find expiring grants

  // ═══════════════════════════════════════════════════════════════════════════════
  // BETTER AUTH TABLES
  // User authentication, sessions, OAuth providers, and API keys
  // ═══════════════════════════════════════════════════════════════════════════════

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Users - Better Auth user accounts with Suna extensions
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  users: defineTable({
    // Base Better Auth fields
    id: v.string(),
    name: v.optional(v.string()),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),

    // Suna extension fields
    tier: v.optional(v.string()), // "free" | "starter" | "pro" | "enterprise"
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    trialEndsAt: v.optional(v.number()),
    preferences: v.optional(v.any()), // Flexible preferences object
  })
    .index("by_email", ["email"])
    .index("by_stripeCustomerId", ["stripeCustomerId"])
    .index("by_stripeSubscriptionId", ["stripeSubscriptionId"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Sessions - Better Auth user sessions with CSRF protection
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  sessions: defineTable({
    id: v.string(),
    userId: v.string(),
    expiresAt: v.number(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),

    // CSRF protection
    csrfToken: v.optional(v.string()),

    // Admin impersonation tracking
    impersonatedBy: v.optional(v.string()), // Admin user ID
  })
    .index("by_userId", ["userId"])
    .index("by_csrfToken", ["csrfToken"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Accounts - Better Auth OAuth/provider accounts
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  accounts: defineTable({
    id: v.string(),
    userId: v.string(),
    accountId: v.string(),
    providerId: v.string(), // "github" | "google" | "credentials"
    accessToken: v.optional(v.string()),
    refreshToken: v.optional(v.string()),
    idToken: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
    password: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),

    // Suna extension fields
    scope: v.optional(v.string()), // OAuth scopes
    tokenType: v.optional(v.string()), // Token type (e.g., "Bearer")
  })
    .index("by_userId", ["userId"])
    .index("by_userId_providerId", ["userId", "providerId"])
    .index("by_accountId_providerId", ["accountId", "providerId"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Verifications - Better Auth verification tokens
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  verifications: defineTable({
    id: v.string(),
    identifier: v.string(), // Email or other identifier
    value: v.string(), // Token value
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),

    // Suna extension fields
    type: v.optional(v.string()), // "email_verification" | "password_reset" | "magic_link"
    usedAt: v.optional(v.number()), // When the token was used
  })
    .index("by_identifier", ["identifier"])
    .index("by_identifier_value", ["identifier", "value"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // API Keys - Service authentication for Python backend
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  apiKeys: defineTable({
    id: v.string(),
    key: v.string(), // Hashed API key
    prefix: v.string(), // Key prefix for identification (e.g., "sk_live_")
    userId: v.optional(v.string()), // User ID (null for service keys)
    name: v.string(), // Key name/description
    scopes: v.array(v.string()), // Permission scopes
    expiresAt: v.optional(v.number()),
    lastUsedAt: v.optional(v.number()),
    createdAt: v.number(),
    revokedAt: v.optional(v.number()),
  })
    .index("by_key", ["key"])
    .index("by_userId", ["userId"])
    .index("by_prefix", ["prefix"]),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Rate Limits - API usage tracking for rate limiting
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  rateLimits: defineTable({
    id: v.string(),
    identifier: v.string(), // IP, user ID, or API key
    endpoint: v.string(), // API endpoint or action
    count: v.number(),
    windowStart: v.number(),
    expiresAt: v.number(),
  })
    .index("by_identifier_endpoint", ["identifier", "endpoint"])
    .index("by_expiresAt", ["expiresAt"]),

  // ═══════════════════════════════════════════════════════════════════════════════
  // KNOWLEDGE BASE TABLES
  // ═══════════════════════════════════════════════════════════════════════════════

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Knowledge Base Folders - Organization for knowledge entries
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  knowledgeBaseFolders: defineTable({
    // Identity
    folderId: v.string(), // Unique folder ID

    // Ownership
    accountId: v.string(), // Reference to account

    // Content
    name: v.string(),
    description: v.optional(v.string()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_folderId", ["folderId"]) // Unique lookup
    .index("by_account", ["accountId"]) // Account's folders
    .index("by_account_created", ["accountId", "createdAt"]), // Chronological

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Knowledge Base Entries - Files and documents in knowledge base
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  knowledgeBaseEntries: defineTable({
    // Identity
    entryId: v.string(), // Unique entry ID

    // Ownership
    accountId: v.string(), // Reference to account

    // Folder association
    folderId: v.string(), // Parent folder

    // File info
    filename: v.string(),
    fileType: v.optional(v.string()), // MIME type
    fileSize: v.number(), // Size in bytes

    // Storage
    storagePath: v.string(), // Path in storage (S3/Convex storage)

    // Content
    summary: v.optional(v.string()), // AI-generated summary

    // Processing status
    status: v.string(), // 'pending', 'processing', 'completed', 'failed'
    processingError: v.optional(v.string()),

    // Active flag for soft delete
    isActive: v.boolean(),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_entryId", ["entryId"]) // Unique lookup
    .index("by_account", ["accountId"]) // Account's entries
    .index("by_folder", ["folderId"]) // Folder's entries
    .index("by_account_folder", ["accountId", "folderId"]) // Account + folder
    .index("by_account_active", ["accountId", "isActive"]) // Active entries
    .index("by_status", ["status"]) // Filter by status
    .searchIndex("by_summary", {
      searchField: "summary",
      filterFields: ["accountId", "folderId", "isActive"],
    }),

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Agent Knowledge Entry Assignments - Links agents to KB entries
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  agentKnowledgeEntryAssignments: defineTable({
    // Identity
    assignmentId: v.string(), // Unique assignment ID

    // Associations
    agentId: v.string(), // Agent reference
    entryId: v.string(), // KB entry reference

    // Ownership (for efficient queries)
    accountId: v.string(),

    // Timestamps
    createdAt: v.number(),
  })
    .index("by_assignmentId", ["assignmentId"]) // Unique lookup
    .index("by_agent", ["agentId"]) // Agent's assignments
    .index("by_entry", ["entryId"]) // Entry's assignments
    .index("by_agent_entry", ["agentId", "entryId"]), // Check specific assignment
});
