/**
 * The skills every Kortix project ships with.
 *
 * GENERATED BY HAND FROM REAL FILES, not invented: every entry below is one
 * `SKILL.md` under packages/starter/templates/base/.kortix/opencode/skills/,
 * with that file's own `name` and `description` frontmatter verbatim.
 * demo-content.test.ts re-reads those files and fails if this drifts.
 *
 * Used by the signed-out Skills preview, which cannot fetch anything: the
 * project-scoped config endpoint needs a session, so the only honest content
 * is the starter template that every real project is created from.
 */

import type { SkillEntity } from '@/features/workspace/skills/skill-entities';

/** Path of the starter template these are read from, relative to the repo root. */
export const DEMO_SKILLS_SOURCE = 'packages/starter/templates/base/.kortix/opencode/skills';

export const DEMO_SKILLS: readonly SkillEntity[] = [
  {
    name: 'kortix-executor',
    path: '.kortix/opencode/skills/kortix-executor/SKILL.md',
    description:
      'Use the Kortix Executor to reach external systems from a session. Prefer the `kortix executor` CLI for agent work, use `@kortix/executor-sdk` for durable TypeScript workflows and reusable skills, and treat the `kortix executor mcp` server as an optional compatibility face. Load whenever the user asks the agent to act in an external app/API, inspect available connectors/tools, add/configure a connector, or work with `connectors:` in kortix.yaml.',
  },
  {
    name: 'kortix-marketplace',
    path: '.kortix/opencode/skills/kortix-marketplace/SKILL.md',
    description:
      "The Kortix marketplace — how to discover capabilities and IMPORT them into this project. The marketplace is a catalog of open git repos: whole ready-made PROJECTS (registry:project) and individual skills/agents/tools. There is no deterministic 'installer' — you (the agent) import an item by reading its source and merging the files that fit into this project, then opening a change request. Use when the user wants to browse/search the Kortix catalog, 'add/clone the <X> project', 'import that skill/agent', pull in a marketplace capability, or add a new source. For the open npx-skills ecosystem, see find-skills-sh.",
  },
  {
    name: 'kortix-memory',
    path: '.kortix/opencode/skills/kortix-memory/SKILL.md',
    description:
      'How to read, write, and curate project memory in `.kortix/memory/` — the project brain. Load this skill whenever you (or the memory-reflector agent) need to add, update, or reorganize what this project knows about itself. Defines the rubric for what belongs in memory, the file structure, and the change-request flow for landing memory edits on `main`.',
  },
  {
    name: 'kortix-onboarding',
    path: '.kortix/opencode/skills/kortix-onboarding/SKILL.md',
    description:
      "Guide a new Kortix user through their first session: set expectations about what Kortix is, turn a vague ask into a strong first prompt, deliver one real result, then surface deeper capabilities (connectors, memory, triggers, subagents, marketplace) and plant a retention hook. Use when the user is new, asks 'what can you do / how does this work / where do I start', sends a vague or exploratory first message, or has no prior history in this project. Do NOT use when they arrive with a specific, well-formed task — just do it.",
  },
  {
    name: 'kortix-slack',
    path: '.kortix/opencode/skills/kortix-slack/SKILL.md',
    description:
      'How to CONNECT Slack (one command — `kortix channels connect`, prints a one-click install link) and how to answer in Slack as a teammate. Covers the live plan-block stream (`slack step` with --detail/--output, `slack send` to finalize the answer), file uploads, posting to other channels/threads, reactions, search, message editing/deletion, and the tone the bot should use. Load this when the user asks to connect/set up Slack, when the turn is triggered from Slack (the prompt mentions a Slack workspace/channel/thread, or `$SLACK_CHANNEL_ID` is set in the env), or when the user asks how to do anything in Slack.',
  },
  {
    name: 'kortix-system',
    path: '.kortix/opencode/skills/kortix-system/SKILL.md',
    description:
      "Canonical reference for a Kortix project: what Kortix can do (research and the web, browser automation, code and data execution, documents and media, websites and apps, connectors/integrations, secrets, memory, scheduling, channels, parallel subagents, model selection) and how the platform works under the hood — repo-native projects, sessions on ephemeral branches, the strict boundary between `kortix.yaml` and OpenCode config under `.kortix/opencode/`; the full `kortix.yaml` manifest (keys, `triggers:` fields incl. cron/webhook/one-off scheduling and `session_mode`, secrets contract, `apps:` deploy surface); the complete `kortix` CLI (commands, flags, the project-scoped token model, the in-sandbox `KORTIX_SANDBOX_TOKEN`); the change-request (CR) system for landing session work on `main` (an agent MUST open a CR to merge); the session sandbox runtime (which supports Docker and Docker-in-Docker); and the OpenCode runtime (agents, skills, commands, tools, plugins, MCP servers, permissions, AGENTS.md rules, models). Load whenever the user asks how Kortix works, what Kortix/it can do, 'can you do X', how to do Y in Kortix, how Kortix compares to other AI tools/assistants, about `kortix.yaml`, the `kortix` CLI, anything under `.kortix/opencode/`, how to merge/ship/land work on `main`, change requests/CRs/PRs, how to author/edit any OpenCode primitive, or how to schedule something — recurring/cron jobs, one-off reminders, run-later, webhooks, or automations.",
  },
  {
    name: 'kortix-teams',
    path: '.kortix/opencode/skills/kortix-teams/SKILL.md',
    description:
      'How to answer in Microsoft Teams as a teammate. Covers the live Adaptive Card stream (`teams step` with --detail/--output/--source, `teams send` to finalize the answer), sending and downloading files (the consent-card upload flow + `teams download`), reading teams/channels/members via the Executor, asking the user, and the tone the bot should use. Load this when the turn is triggered from Teams (the prompt mentions a Teams tenant/conversation, or `$MS_TEAMS_CONVERSATION_ID` is set in the env), or when the user asks how to do anything in Teams.',
  },
  {
    name: 'kortix-voice',
    path: '.kortix/opencode/skills/kortix-voice/SKILL.md',
    description:
      'How to work a live voice call from inside a session — start one and share the join link, follow what is being said without blocking, speak into the room, and hang up. The call IS this session, so no call id is ever passed. Load this WHENEVER the user asks to start a call, "call me", talk out loud, or asks anything about the voice channel, and whenever a turn arrives from a live call.',
  },
];
