-- Migration: capture
--
-- SAFETY HEADER (house rules -- see packages/db/MIGRATIONS.md#zero-downtime-rules).
-- Tune these down further for large/hot tables; raise statement_timeout only
-- for an operation you've deliberately reasoned about (e.g. a NOT VALID
-- constraint's later VALIDATE, or a batched backfill with its own paging).
set lock_timeout = '2s';
set statement_timeout = '30s';

-- REVIEW THE GENERATED SQL BELOW. drizzle-kit writes it from the diff between
-- kortix.ts and the snapshot; it knows the target shape, not how to reach it
-- without downtime. Check the same list `migrate:create` prints:
--   [ ] Bare NOT NULL added to an existing populated table (needs a backfill first).
--   [ ] Plain CREATE INDEX / DROP INDEX on an EXISTING table -- move it to
--       `pnpm migrate:create <slug> --concurrent`; it blocks writes here.
--   [ ] New FK/constraint on an existing table -- add NOT VALID, VALIDATE after.
--   [ ] A DROP/RENAME/ALTER ... TYPE the generator proposed from a STALE
--       snapshot. Delete anything already applied by an earlier migration.
--   [ ] Any DROP/RENAME/ALTER ... TYPE/DROP NOT NULL needs the enforced line:
-- mixed-version-safe: <why old code tolerates this change, or why it cannot still be running>
--   [ ] Any ALTER TYPE ... ADD VALUE needs:
-- enum-value-checked: <how you verified every env, including any faked baseline, has this value>

CREATE TABLE "kortix"."capture_account_settings" (
	"account_id" uuid PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"admins_can_view" boolean DEFAULT false NOT NULL,
	"retention_days" integer DEFAULT 30 NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "capture_account_settings_retention_check" CHECK ("kortix"."capture_account_settings"."retention_days" BETWEEN 1 AND 3650)
);
--> statement-breakpoint
CREATE TABLE "kortix"."capture_chunks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"device_id" uuid NOT NULL,
	"client_uid" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone NOT NULL,
	"frame_count" integer NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"codec" text NOT NULL,
	"video_key" text NOT NULL,
	"video_bytes" bigint NOT NULL,
	"video_sha256" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"committed_at" timestamp with time zone,
	CONSTRAINT "capture_chunks_device_client_uid_unique" UNIQUE("device_id","client_uid"),
	CONSTRAINT "capture_chunks_status_check" CHECK ("kortix"."capture_chunks"."status" IN ('pending', 'committed')),
	CONSTRAINT "capture_chunks_codec_check" CHECK ("kortix"."capture_chunks"."codec" IN ('hevc', 'h264'))
);
--> statement-breakpoint
CREATE TABLE "kortix"."capture_devices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"tunnel_id" uuid,
	"enabled" boolean DEFAULT false NOT NULL,
	"paused_until" timestamp with time zone,
	"last_upload_at" timestamp with time zone,
	"last_seen_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "capture_devices_tunnel_id_unique" UNIQUE("tunnel_id")
);
--> statement-breakpoint
CREATE TABLE "kortix"."capture_frames" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"chunk_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"frame_index" integer NOT NULL,
	"app_bundle" text,
	"app_name" text,
	"window_title" text,
	"url" text,
	"domain" text,
	"text" text,
	"tsv" tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(window_title,'') || ' ' || coalesce(text,''))) STORED,
	CONSTRAINT "capture_frames_chunk_index_unique" UNIQUE("chunk_id","frame_index")
);
--> statement-breakpoint
ALTER TABLE "kortix"."capture_account_settings" ADD CONSTRAINT "capture_account_settings_account_id_accounts_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "kortix"."accounts"("account_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kortix"."capture_chunks" ADD CONSTRAINT "capture_chunks_account_id_accounts_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "kortix"."accounts"("account_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kortix"."capture_chunks" ADD CONSTRAINT "capture_chunks_device_id_capture_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "kortix"."capture_devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kortix"."capture_devices" ADD CONSTRAINT "capture_devices_account_id_accounts_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "kortix"."accounts"("account_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kortix"."capture_devices" ADD CONSTRAINT "capture_devices_tunnel_id_tunnel_connections_tunnel_id_fk" FOREIGN KEY ("tunnel_id") REFERENCES "kortix"."tunnel_connections"("tunnel_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kortix"."capture_frames" ADD CONSTRAINT "capture_frames_chunk_id_capture_chunks_id_fk" FOREIGN KEY ("chunk_id") REFERENCES "kortix"."capture_chunks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_capture_chunks_user_started" ON "kortix"."capture_chunks" USING btree ("account_id","user_id","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_capture_chunks_started" ON "kortix"."capture_chunks" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "idx_capture_devices_user" ON "kortix"."capture_devices" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_capture_frames_user_ts" ON "kortix"."capture_frames" USING btree ("account_id","user_id","ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_capture_frames_tsv" ON "kortix"."capture_frames" USING gin ("tsv");
-- API-owned tables: object keys and OCR text are private. Browser roles cannot
-- read or write them, even if a later blanket grant adds table privileges.
REVOKE ALL ON TABLE "kortix"."capture_account_settings", "kortix"."capture_devices", "kortix"."capture_chunks", "kortix"."capture_frames" FROM anon, authenticated;
ALTER TABLE "kortix"."capture_account_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kortix"."capture_devices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kortix"."capture_chunks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kortix"."capture_frames" ENABLE ROW LEVEL SECURITY;

-- Local dev, preview and self-host store capture video in Supabase Storage's
-- S3 endpoint (dev/staging/prod use the Terraform bucket). Private, policy-free,
-- 200 MiB per object = MAX_VIDEO_BYTES in apps/api/src/capture/. Guarded like
-- 20260925105649894_config_releases_bucket.sql: a no-op where Storage is absent.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'storage' and table_name = 'buckets' and column_name = 'public'
  ) then
    raise notice 'storage.buckets not present or unexpected shape — skipping capture bucket setup.';
    return;
  end if;

  insert into storage.buckets (id, name, public, file_size_limit)
  values ('kortix-capture', 'kortix-capture', false, 209715200)
  on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit;
end $$;
