/**
 * Shared session UI primitives — framework-agnostic.
 *
 * Import from '@/ui' for types, turn grouping, part helpers, and status text.
 * The turn helpers live in `@kortix/sdk` (single implementation shared with
 * mobile); this barrel re-exports them by name alongside the web view-model
 * types. The names are enumerated rather than star-exported so the barrel's
 * surface stays explicit and `./types` keeps ownership of the four names it
 * already re-exports itself (Diagnostic, RetryInfo, ToolInfo, TurnCostInfo).
 *
 * IMPORTANT: No React / DOM / framework imports in this folder.
 */

export * from './types';
export {
  allDescendantIds,
  childMapByParent,
  classifyPart,
  classifyTurn,
  collectTurnParts,
  compareMessagesForDisplay,
  computeStatusFromPart,
  COST_MARKUP,
  extractGatewayErrorDetails,
  findLastTextPart,
  formatCost,
  formatDuration,
  formatTokens,
  getAgentCardLabel,
  getAnsweredQuestionParts,
  getChildSessionError,
  getChildSessionId,
  getChildSessionToolParts,
  getDiagnostics,
  getDirectory,
  getFilename,
  getFileWithDir,
  getHiddenToolParts,
  getPartText,
  getPermissionForTool,
  getQuestionForTool,
  getRetryInfo,
  getRetryMessage,
  getSessionCost,
  getShellModePart,
  getToolInfo,
  getTurnCost,
  getTurnError,
  getTurnErrorDetails,
  getTurnStatus,
  getWorkingState,
  groupMessagesIntoTurns,
  hasDiffs,
  hasRetryingAssistantTurn,
  humanizeToolName,
  isAgentPart,
  isAttachment,
  isCompactionPart,
  isFilePart,
  isLastUserMessage,
  isPatchPart,
  isReasoningPart,
  isRetryableTurnError,
  isShellMode,
  isSnapshotPart,
  isTextPart,
  isToolPart,
  isToolPartHidden,
  normalizeToolName,
  relativizePath,
  shellExitCode,
  shouldHideResponsePart,
  shouldShowToolPart,
  sortSessions,
  splitUserParts,
  stripAnsi,
  toolInfo,
  toolViewModel,
  turnHasSteps,
  unwrapError,
} from '@kortix/sdk';
export type {
  ClassifiedAgentPart,
  ClassifiedCompactionPart,
  ClassifiedFilePart,
  ClassifiedPart,
  ClassifiedPatchPart,
  ClassifiedReasoningPart,
  ClassifiedRetryPart,
  ClassifiedSnapshotPart,
  ClassifiedStepPart,
  ClassifiedSubtaskPart,
  ClassifiedTextPart,
  ClassifiedToolPart,
  ClassifiedTurn,
  ClassifiedUnknownPart,
  DiffLine,
  DiffLineType,
  GatewayAttemptFailure,
  GatewayErrorDetails,
  HiddenToolRef,
  MessageInfoLike,
  MessageWithPartsLike,
  ModelCostRates,
  ModelCostTierRates,
  ModelPricingLookup,
  OpenTurnMessageLike,
  PartLike,
  PartWithMessage,
  QuestionItem,
  RequestWithToolLike,
  SearchMatch,
  SessionStatusLike,
  TodoItem,
  TokenUsageLike,
  ToolCategory,
  ToolInfoEntry,
  ToolPartLike,
  ToolStateLike,
  ToolStatus,
  ToolView,
  ToolViewModel,
  TurnError,
  TurnLike,
  WebSearchResultItem,
} from '@kortix/sdk';
export type { QuestionOption } from '@kortix/sdk';
