// This file is auto-generated. Do not edit this file manually.
// To regenerate the schema, run:
// `pnpm --filter kortix-convex gen:auth-schema`

import {
  arrayOf,
  boolean,
  convexTable,
  defineSchema,
  index,
  integer,
  text,
  timestamp,
  uniqueIndex,
} from "kitcn/orm";

export const userTable = convexTable(
  "user",
  {
    name: text().notNull(),
    email: text().notNull().unique(),
    emailVerified: boolean().notNull(),
    image: text(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp().notNull(),
    userId: text(),
    role: text(),
    banned: boolean(),
    banReason: text(),
    banExpires: timestamp(),
    twoFactorEnabled: boolean(),
    phoneNumber: text().unique(),
    phoneNumberVerified: boolean(),
    username: text().unique(),
    displayUsername: text(),
    isAnonymous: boolean(),
    lastActiveOrganizationId: text().references(() => organizationTable.id),
    personalOrganizationId: text().references(() => organizationTable.id),
  },
  (userTable) => [
    index("email_name").on(userTable.email, userTable.name),
    index("name").on(userTable.name),
    index("lastActiveOrganizationId").on(userTable.lastActiveOrganizationId),
    index("personalOrganizationId").on(userTable.personalOrganizationId),
  ]
);

export const sessionTable = convexTable(
  "session",
  {
    expiresAt: timestamp().notNull(),
    token: text().notNull().unique(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp().notNull(),
    ipAddress: text(),
    userAgent: text(),
    userId: text().notNull().references(() => userTable.id),
    activeOrganizationId: text().references(() => organizationTable.id),
    activeTeamId: text().references(() => teamTable.id),
    impersonatedBy: text(),
  },
  (sessionTable) => [
    index("expiresAt").on(sessionTable.expiresAt),
    index("expiresAt_userId").on(sessionTable.expiresAt, sessionTable.userId),
    index("userId").on(sessionTable.userId),
    index("activeOrganizationId").on(sessionTable.activeOrganizationId),
    index("activeTeamId").on(sessionTable.activeTeamId),
  ]
);

export const accountTable = convexTable(
  "account",
  {
    issuer: text().notNull(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text().notNull().references(() => userTable.id),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp(),
    refreshTokenExpiresAt: timestamp(),
    scope: text(),
    password: text(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp().notNull(),
  },
  (accountTable) => [
    index("accountId").on(accountTable.accountId),
    index("accountId_providerId").on(accountTable.accountId, accountTable.providerId),
    index("providerId_userId").on(accountTable.providerId, accountTable.userId),
    uniqueIndex("issuer_accountId").on(accountTable.issuer, accountTable.accountId),
    index("userId").on(accountTable.userId),
  ]
);

export const verificationTable = convexTable(
  "verification",
  {
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp().notNull(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp().notNull(),
  },
  (verificationTable) => [
    index("expiresAt").on(verificationTable.expiresAt),
    index("identifier").on(verificationTable.identifier),
  ]
);

export const jwksTable = convexTable(
  "jwks",
  {
    publicKey: text().notNull(),
    privateKey: text().notNull(),
    createdAt: timestamp().notNull(),
    expiresAt: timestamp(),
    alg: text(),
    crv: text(),
  }
);

export const organizationTable = convexTable(
  "organization",
  {
    name: text().notNull(),
    slug: text().notNull().unique(),
    logo: text(),
    createdAt: timestamp().notNull(),
    metadata: text(),
  },
  (organizationTable) => [
    index("name").on(organizationTable.name),
  ]
);

export const organizationRoleTable = convexTable(
  "organizationRole",
  {
    organizationId: text().notNull().references(() => organizationTable.id),
    role: text().notNull(),
    permission: text().notNull(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp(),
  },
  (organizationRoleTable) => [
    index("organizationId").on(organizationRoleTable.organizationId),
    index("organizationId_role").on(organizationRoleTable.organizationId, organizationRoleTable.role),
  ]
);

export const teamTable = convexTable(
  "team",
  {
    name: text().notNull(),
    memberCount: integer().notNull(),
    organizationId: text().notNull().references(() => organizationTable.id),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp(),
  },
  (teamTable) => [
    index("organizationId").on(teamTable.organizationId),
  ]
);

export const teamMemberTable = convexTable(
  "teamMember",
  {
    teamId: text().notNull().references(() => teamTable.id),
    userId: text().notNull().references(() => userTable.id),
    membershipKey: text().unique(),
    createdAt: timestamp(),
  },
  (teamMemberTable) => [
    index("teamId").on(teamMemberTable.teamId),
    index("teamId_userId").on(teamMemberTable.teamId, teamMemberTable.userId),
    index("userId").on(teamMemberTable.userId),
  ]
);

export const memberTable = convexTable(
  "member",
  {
    organizationId: text().notNull().references(() => organizationTable.id),
    userId: text().notNull().references(() => userTable.id),
    role: text().notNull(),
    createdAt: timestamp().notNull(),
  },
  (memberTable) => [
    index("organizationId").on(memberTable.organizationId),
    index("organizationId_role").on(memberTable.organizationId, memberTable.role),
    index("organizationId_userId").on(memberTable.organizationId, memberTable.userId),
    index("userId").on(memberTable.userId),
    index("role").on(memberTable.role),
  ]
);

export const invitationTable = convexTable(
  "invitation",
  {
    organizationId: text().notNull().references(() => organizationTable.id),
    email: text().notNull(),
    role: text(),
    teamId: text().references(() => teamTable.id),
    status: text().notNull(),
    expiresAt: timestamp().notNull(),
    createdAt: timestamp().notNull(),
    inviterId: text().notNull().references(() => userTable.id),
  },
  (invitationTable) => [
    index("email").on(invitationTable.email),
    index("email_organizationId_status").on(invitationTable.email, invitationTable.organizationId, invitationTable.status),
    index("organizationId").on(invitationTable.organizationId),
    index("organizationId_status").on(invitationTable.organizationId, invitationTable.status),
    index("role").on(invitationTable.role),
    index("teamId").on(invitationTable.teamId),
    index("status").on(invitationTable.status),
    index("inviterId").on(invitationTable.inviterId),
  ]
);

export const apikeyTable = convexTable(
  "apikey",
  {
    configId: text().notNull(),
    name: text(),
    start: text(),
    referenceId: text().notNull(),
    prefix: text(),
    key: text().notNull(),
    refillInterval: integer(),
    refillAmount: integer(),
    lastRefillAt: timestamp(),
    enabled: boolean(),
    rateLimitEnabled: boolean(),
    rateLimitTimeWindow: integer(),
    rateLimitMax: integer(),
    requestCount: integer(),
    remaining: integer(),
    lastRequest: timestamp(),
    expiresAt: timestamp(),
    createdAt: timestamp().notNull(),
    updatedAt: timestamp().notNull(),
    permissions: text(),
    metadata: text(),
  }
);

export const twoFactorTable = convexTable(
  "twoFactor",
  {
    secret: text().notNull(),
    backupCodes: text().notNull(),
    userId: text().notNull().references(() => userTable.id),
    verified: boolean(),
    failedVerificationCount: integer(),
    lockedUntil: timestamp(),
  },
  (twoFactorTable) => [
    index("userId").on(twoFactorTable.userId),
  ]
);

export const passkeyTable = convexTable(
  "passkey",
  {
    name: text(),
    publicKey: text().notNull(),
    userId: text().notNull().references(() => userTable.id),
    credentialID: text().notNull(),
    counter: integer().notNull(),
    deviceType: text().notNull(),
    backedUp: boolean().notNull(),
    transports: text(),
    createdAt: timestamp(),
    aaguid: text(),
  },
  (passkeyTable) => [
    index("credentialID").on(passkeyTable.credentialID),
    index("userId").on(passkeyTable.userId),
  ]
);

export const oauthClientTable = convexTable(
  "oauthClient",
  {
    clientId: text().notNull().unique(),
    clientSecret: text(),
    clientDiscoveryId: text(),
    disabled: boolean(),
    skipConsent: boolean(),
    enableEndSession: boolean(),
    subjectType: text(),
    scopes: arrayOf(text().notNull()),
    clientCredentialsScopes: arrayOf(text().notNull()),
    userId: text().references(() => userTable.id),
    createdAt: timestamp(),
    updatedAt: timestamp(),
    name: text(),
    uri: text(),
    icon: text(),
    contacts: arrayOf(text().notNull()),
    tos: text(),
    policy: text(),
    softwareId: text(),
    softwareVersion: text(),
    softwareStatement: text(),
    redirectUris: arrayOf(text().notNull()).notNull(),
    postLogoutRedirectUris: arrayOf(text().notNull()),
    backchannelLogoutUri: text(),
    backchannelLogoutSessionRequired: boolean(),
    tokenEndpointAuthMethod: text(),
    applicationType: text(),
    jwks: text(),
    jwksUri: text(),
    grantTypes: arrayOf(text().notNull()),
    responseTypes: arrayOf(text().notNull()),
    requirePKCE: boolean(),
    dpopBoundAccessTokens: boolean(),
    referenceId: text(),
    metadata: text(),
  },
  (oauthClientTable) => [
    index("userId").on(oauthClientTable.userId),
  ]
);

export const oauthResourceTable = convexTable(
  "oauthResource",
  {
    identifier: text().notNull().unique(),
    name: text().notNull(),
    accessTokenTtl: integer(),
    refreshTokenTtl: integer(),
    signingAlgorithm: text(),
    signingKeyId: text(),
    allowedScopes: arrayOf(text().notNull()),
    customClaims: text(),
    dpopBoundAccessTokensRequired: boolean(),
    disabled: boolean(),
    createdAt: timestamp(),
    updatedAt: timestamp(),
    policyVersion: integer(),
    metadata: text(),
  }
);

export const oauthClientResourceTable = convexTable(
  "oauthClientResource",
  {
    clientId: text().notNull().references(() => oauthClientTable.clientId),
    resourceId: text().notNull().references(() => oauthResourceTable.identifier),
    metadata: text(),
    createdAt: timestamp(),
  },
  (oauthClientResourceTable) => [
    uniqueIndex("clientId_resourceId").on(oauthClientResourceTable.clientId, oauthClientResourceTable.resourceId),
    index("resourceId").on(oauthClientResourceTable.resourceId),
  ]
);

export const oauthRefreshTokenTable = convexTable(
  "oauthRefreshToken",
  {
    token: text().notNull().unique(),
    clientId: text().notNull().references(() => oauthClientTable.clientId),
    sessionId: text().references(() => sessionTable.id),
    userId: text().notNull().references(() => userTable.id),
    referenceId: text(),
    authorizationCodeId: text(),
    resources: arrayOf(text().notNull()),
    requestedUserInfoClaims: arrayOf(text().notNull()),
    expiresAt: timestamp(),
    createdAt: timestamp(),
    revoked: timestamp(),
    rotatedAt: timestamp(),
    rotationReplayResponse: text(),
    rotationReplayExpiresAt: timestamp(),
    authTime: timestamp(),
    confirmation: text(),
    scopes: arrayOf(text().notNull()).notNull(),
  },
  (oauthRefreshTokenTable) => [
    index("clientId").on(oauthRefreshTokenTable.clientId),
    index("sessionId").on(oauthRefreshTokenTable.sessionId),
    index("userId").on(oauthRefreshTokenTable.userId),
  ]
);

export const oauthAccessTokenTable = convexTable(
  "oauthAccessToken",
  {
    token: text().unique(),
    clientId: text().notNull().references(() => oauthClientTable.clientId),
    sessionId: text().references(() => sessionTable.id),
    userId: text().references(() => userTable.id),
    referenceId: text(),
    authorizationCodeId: text(),
    resources: arrayOf(text().notNull()),
    requestedUserInfoClaims: arrayOf(text().notNull()),
    refreshId: text().references(() => oauthRefreshTokenTable.id),
    expiresAt: timestamp(),
    createdAt: timestamp(),
    revoked: timestamp(),
    confirmation: text(),
    scopes: arrayOf(text().notNull()).notNull(),
  },
  (oauthAccessTokenTable) => [
    index("clientId").on(oauthAccessTokenTable.clientId),
    index("sessionId").on(oauthAccessTokenTable.sessionId),
    index("userId").on(oauthAccessTokenTable.userId),
    index("refreshId").on(oauthAccessTokenTable.refreshId),
  ]
);

export const oauthConsentTable = convexTable(
  "oauthConsent",
  {
    clientId: text().notNull().references(() => oauthClientTable.clientId),
    userId: text().references(() => userTable.id),
    referenceId: text(),
    resources: arrayOf(text().notNull()),
    requestedUserInfoClaims: arrayOf(text().notNull()),
    scopes: arrayOf(text().notNull()).notNull(),
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  (oauthConsentTable) => [
    index("clientId_userId").on(oauthConsentTable.clientId, oauthConsentTable.userId),
    index("userId").on(oauthConsentTable.userId),
  ]
);

export const oauthClientAssertionTable = convexTable(
  "oauthClientAssertion",
  {
    expiresAt: timestamp().notNull(),
  }
);

export const deviceCodeTable = convexTable(
  "deviceCode",
  {
    deviceCode: text().notNull(),
    userCode: text().notNull(),
    userId: text(),
    expiresAt: timestamp().notNull(),
    status: text().notNull(),
    lastPolledAt: timestamp(),
    pollingInterval: integer(),
    clientId: text(),
    scope: text(),
  },
  (deviceCodeTable) => [
    uniqueIndex("deviceCode").on(deviceCodeTable.deviceCode),
    uniqueIndex("userCode").on(deviceCodeTable.userCode),
  ]
);

export const tables = {
  user: userTable,
  session: sessionTable,
  account: accountTable,
  verification: verificationTable,
  jwks: jwksTable,
  organization: organizationTable,
  organizationRole: organizationRoleTable,
  team: teamTable,
  teamMember: teamMemberTable,
  member: memberTable,
  invitation: invitationTable,
  apikey: apikeyTable,
  twoFactor: twoFactorTable,
  passkey: passkeyTable,
  oauthClient: oauthClientTable,
  oauthResource: oauthResourceTable,
  oauthClientResource: oauthClientResourceTable,
  oauthRefreshToken: oauthRefreshTokenTable,
  oauthAccessToken: oauthAccessTokenTable,
  oauthConsent: oauthConsentTable,
  oauthClientAssertion: oauthClientAssertionTable,
  deviceCode: deviceCodeTable,
};

const schema = defineSchema(tables).relations((r) => ({
  user: {
    lastActiveOrganization: r.one.organization({
      from: r.user.lastActiveOrganizationId,
      to: r.organization.id,
      alias: "lastActiveOrganization",
    }),
    personalOrganization: r.one.organization({
      from: r.user.personalOrganizationId,
      to: r.organization.id,
      alias: "personalOrganization",
    }),
    sessions: r.many.session({
      from: r.user.id,
      to: r.session.userId,
    }),
    accounts: r.many.account({
      from: r.user.id,
      to: r.account.userId,
    }),
    teamMembers: r.many.teamMember({
      from: r.user.id,
      to: r.teamMember.userId,
    }),
    members: r.many.member({
      from: r.user.id,
      to: r.member.userId,
    }),
    invitations: r.many.invitation({
      from: r.user.id,
      to: r.invitation.inviterId,
    }),
    twoFactors: r.many.twoFactor({
      from: r.user.id,
      to: r.twoFactor.userId,
    }),
    passkeys: r.many.passkey({
      from: r.user.id,
      to: r.passkey.userId,
    }),
    oauthClients: r.many.oauthClient({
      from: r.user.id,
      to: r.oauthClient.userId,
    }),
    oauthRefreshTokens: r.many.oauthRefreshToken({
      from: r.user.id,
      to: r.oauthRefreshToken.userId,
    }),
    oauthAccessTokens: r.many.oauthAccessToken({
      from: r.user.id,
      to: r.oauthAccessToken.userId,
    }),
    oauthConsents: r.many.oauthConsent({
      from: r.user.id,
      to: r.oauthConsent.userId,
    }),
  },
  session: {
    user: r.one.user({
      from: r.session.userId,
      to: r.user.id,
    }),
    activeOrganization: r.one.organization({
      from: r.session.activeOrganizationId,
      to: r.organization.id,
    }),
    activeTeam: r.one.team({
      from: r.session.activeTeamId,
      to: r.team.id,
    }),
    oauthRefreshTokens: r.many.oauthRefreshToken({
      from: r.session.id,
      to: r.oauthRefreshToken.sessionId,
    }),
    oauthAccessTokens: r.many.oauthAccessToken({
      from: r.session.id,
      to: r.oauthAccessToken.sessionId,
    }),
  },
  account: {
    user: r.one.user({
      from: r.account.userId,
      to: r.user.id,
    }),
  },
  organization: {
    usersAsLastActiveOrganization: r.many.user({
      from: r.organization.id,
      to: r.user.lastActiveOrganizationId,
      alias: "lastActiveOrganization",
    }),
    usersAsPersonalOrganization: r.many.user({
      from: r.organization.id,
      to: r.user.personalOrganizationId,
      alias: "personalOrganization",
    }),
    sessions: r.many.session({
      from: r.organization.id,
      to: r.session.activeOrganizationId,
    }),
    organizationRoles: r.many.organizationRole({
      from: r.organization.id,
      to: r.organizationRole.organizationId,
    }),
    teams: r.many.team({
      from: r.organization.id,
      to: r.team.organizationId,
    }),
    members: r.many.member({
      from: r.organization.id,
      to: r.member.organizationId,
    }),
    invitations: r.many.invitation({
      from: r.organization.id,
      to: r.invitation.organizationId,
    }),
  },
  organizationRole: {
    organization: r.one.organization({
      from: r.organizationRole.organizationId,
      to: r.organization.id,
    }),
  },
  team: {
    sessions: r.many.session({
      from: r.team.id,
      to: r.session.activeTeamId,
    }),
    organization: r.one.organization({
      from: r.team.organizationId,
      to: r.organization.id,
    }),
    teamMembers: r.many.teamMember({
      from: r.team.id,
      to: r.teamMember.teamId,
    }),
    invitations: r.many.invitation({
      from: r.team.id,
      to: r.invitation.teamId,
    }),
  },
  teamMember: {
    team: r.one.team({
      from: r.teamMember.teamId,
      to: r.team.id,
    }),
    user: r.one.user({
      from: r.teamMember.userId,
      to: r.user.id,
    }),
  },
  member: {
    organization: r.one.organization({
      from: r.member.organizationId,
      to: r.organization.id,
    }),
    user: r.one.user({
      from: r.member.userId,
      to: r.user.id,
    }),
  },
  invitation: {
    organization: r.one.organization({
      from: r.invitation.organizationId,
      to: r.organization.id,
    }),
    team: r.one.team({
      from: r.invitation.teamId,
      to: r.team.id,
    }),
    inviter: r.one.user({
      from: r.invitation.inviterId,
      to: r.user.id,
    }),
  },
  twoFactor: {
    user: r.one.user({
      from: r.twoFactor.userId,
      to: r.user.id,
    }),
  },
  passkey: {
    user: r.one.user({
      from: r.passkey.userId,
      to: r.user.id,
    }),
  },
  oauthClient: {
    user: r.one.user({
      from: r.oauthClient.userId,
      to: r.user.id,
    }),
    oauthClientResources: r.many.oauthClientResource({
      from: r.oauthClient.clientId,
      to: r.oauthClientResource.clientId,
    }),
    oauthRefreshTokens: r.many.oauthRefreshToken({
      from: r.oauthClient.clientId,
      to: r.oauthRefreshToken.clientId,
    }),
    oauthAccessTokens: r.many.oauthAccessToken({
      from: r.oauthClient.clientId,
      to: r.oauthAccessToken.clientId,
    }),
    oauthConsents: r.many.oauthConsent({
      from: r.oauthClient.clientId,
      to: r.oauthConsent.clientId,
    }),
  },
  oauthResource: {
    oauthClientResources: r.many.oauthClientResource({
      from: r.oauthResource.identifier,
      to: r.oauthClientResource.resourceId,
    }),
  },
  oauthClientResource: {
    client: r.one.oauthClient({
      from: r.oauthClientResource.clientId,
      to: r.oauthClient.clientId,
    }),
    resource: r.one.oauthResource({
      from: r.oauthClientResource.resourceId,
      to: r.oauthResource.identifier,
    }),
  },
  oauthRefreshToken: {
    client: r.one.oauthClient({
      from: r.oauthRefreshToken.clientId,
      to: r.oauthClient.clientId,
    }),
    session: r.one.session({
      from: r.oauthRefreshToken.sessionId,
      to: r.session.id,
    }),
    user: r.one.user({
      from: r.oauthRefreshToken.userId,
      to: r.user.id,
    }),
    oauthAccessTokens: r.many.oauthAccessToken({
      from: r.oauthRefreshToken.id,
      to: r.oauthAccessToken.refreshId,
    }),
  },
  oauthAccessToken: {
    client: r.one.oauthClient({
      from: r.oauthAccessToken.clientId,
      to: r.oauthClient.clientId,
    }),
    session: r.one.session({
      from: r.oauthAccessToken.sessionId,
      to: r.session.id,
    }),
    user: r.one.user({
      from: r.oauthAccessToken.userId,
      to: r.user.id,
    }),
    refresh: r.one.oauthRefreshToken({
      from: r.oauthAccessToken.refreshId,
      to: r.oauthRefreshToken.id,
    }),
  },
  oauthConsent: {
    client: r.one.oauthClient({
      from: r.oauthConsent.clientId,
      to: r.oauthClient.clientId,
    }),
    user: r.one.user({
      from: r.oauthConsent.userId,
      to: r.user.id,
    }),
  },
}));

export default schema;

