// GENERATED by desktop/build.mjs — do not edit.
// Every dynamic route in the desktop bundle, most-specific first.
// Consumed by desktop/nav-shim.tsx to recover real params from the URL.
// Committed with a placeholder value so the shim type-checks outside a desktop build.

export const ROUTE_PATTERNS: readonly string[] = [];
