// Centralized copy registry for frontend texts (Russian default)
// All UI strings should be referenced from this object.

export const copy = {
  common: {
    ok: 'ОК',
    cancel: 'Отмена',
    save: 'Сохранить',
    close: 'Закрыть',
    back: 'Назад',
    next: 'Далее',
    loading: 'Загрузка…',
  },
  home: {
    inputPlaceholder: 'Опишите задачу, которую должен выполнить ваш Работник…',
    authDialog: {
      title: 'Войдите, чтобы продолжить',
      description: 'Войдите или создайте аккаунт, чтобы поговорить с Kortix',
      divider: 'или продолжить по email',
      signInEmail: 'Войти по email',
      createAccount: 'Создать новый аккаунт',
      consentPrefix: 'Продолжая, вы соглашаетесь с',
      terms: 'Условиями использования',
      and: 'и',
      privacy: 'Политикой конфиденциальности',
    },
  },
  nav: {
    dashboard: 'Панель',
    agents: 'Агенты',
    threads: 'Диалоги',
    settings: 'Настройки',
    admin: 'Админ‑панель',
    billing: 'Биллинг',
  },
  auth: {
    signIn: 'Войти',
    signOut: 'Выйти',
    signUp: 'Зарегистрироваться',
    email: 'Электронная почта',
    password: 'Пароль',
    forgotPassword: 'Забыли пароль?',
    // Login/Signup page
    titleSignIn: 'Войдите в аккаунт',
    titleSignUp: 'Создайте аккаунт',
    oauthSeparator: 'или email',
    emailPlaceholder: 'Адрес электронной почты',
    passwordPlaceholder: 'Пароль',
    confirmPasswordPlaceholder: 'Подтвердите пароль',
    privacyPolicy: 'Политику конфиденциальности',
    termsOfService: 'Условия использования',
    consentTextPrefix: 'Я принимаю',
    consentTextMiddle: 'и',
    creatingAccountPending: 'Создание аккаунта…',
    signingInPending: 'Вход…',
    createAccount: 'Создать аккаунт',
    signInButton: 'Войти',
    forgotPasswordLink: 'Забыли пароль?',
    toggleToSignIn: 'Уже есть аккаунт? Войти',
    toggleToSignUp: 'Нет аккаунта? Зарегистрироваться',
    // Registration success view
    checkEmailTitle: 'Проверьте почту',
    checkEmailDesc: 'Мы отправили ссылку для подтверждения на:',
    yourEmailAddress: 'ваш адрес электронной почты',
    checkEmailInfo: 'Перейдите по ссылке в письме, чтобы активировать аккаунт. Если письма нет — проверьте папку «Спам».',
    returnHome: 'На главную',
    backToSignIn: 'Вернуться ко входу',
    // Toasts and validation
    loginFailed: 'Не удалось войти',
    signUpFailed: 'Не удалось зарегистрироваться',
    enterValidEmail: 'Введите корректный адрес электронной почты',
    // Reset password dialog
    resetPasswordTitle: 'Сброс пароля',
    resetPasswordDesc: 'Введите адрес электронной почты, и мы отправим ссылку для сброса пароля.',
    resetPasswordSend: 'Отправить ссылку для сброса',
  },
  dashboard: {
    title: 'Панель управления',
    welcome: 'Добро пожаловать в Kortix',
    createAgent: 'Создать агента',
    promptTitle: 'Что вы хотите сделать?',
    inputPlaceholder: 'Опишите, с чем нужна помощь…',
  },
  agents: {
    listTitle: 'Агенты',
    newAgent: 'Новый агент',
    editAgent: 'Редактировать агента',
    deleteAgent: 'Удалить агента',
    noAgents: 'Пока нет созданных агентов',
  },
  threads: {
    newThread: 'Новый диалог',
    continueThread: 'Продолжить диалог',
    emptyState: 'Диалоги ещё не созданы',
  },
  billing: {
    title: 'Биллинг',
    plan: 'Тарифный план',
    changePlan: 'Изменить план',
    paymentMethod: 'Способ оплаты',
    invoices: 'Счета',
    adminTitle: 'Управление биллингом — Админ',
    adminSubtitle: 'Управление биллингом и учетными записями пользователей',
  },
  pricing: {
    title: 'Цены на токены',
    subtitle: 'Разберитесь, как работают токены, изучите цены моделей ИИ и подберите подходящий план.',
    loading: 'Загрузка данных о ценах…',
    unavailableTitle: 'Цены недоступны',
    unavailableDesc: 'Не удалось получить цены моделей. Обновите страницу.',
  },
  apiKeys: {
    title: 'API‑ключи',
    description: 'Управляйте API‑ключами для программного доступа к Kortix',
    headerNote: 'API‑ключи используют пару публичный/секретный ключ для безопасной аутентификации',
    newKey: 'Новый API‑ключ',
    createDialogTitle: 'Создать API‑ключ',
    createDialogDesc: 'Создайте новый API‑ключ для программного доступа к вашему аккаунту.',
    fieldTitle: 'Название *',
    fieldTitlePlaceholder: 'Мой API‑ключ',
    fieldDescription: 'Описание',
    fieldDescriptionPlaceholder: 'Необязательное описание для этого API‑ключа',
    fieldExpires: 'Срок действия',
    expiresNever: 'Без срока действия',
    expires7d: '7 дней',
    expires30d: '30 дней',
    expires90d: '90 дней',
    expires365d: '1 год',
    creating: 'Создание…',
    createButton: 'Создать API‑ключ',
    listLoadFailed: 'Не удалось загрузить API‑ключи. Повторите попытку.',
    emptyTitle: 'Пока нет API‑ключей',
    emptyDesc: 'Создайте первую пару ключей, чтобы начать программно использовать Kortix. Каждый ключ включает публичный идентификатор и секрет для безопасной аутентификации.',
    emptyCreateButton: 'Создать API‑ключ',
    statusActive: 'Активен',
    statusRevoked: 'Отозван',
    statusExpired: 'Истёк',
    cardCreatedLabel: 'Создан',
    cardExpiresLabel: 'Истекает',
    cardLastUsedLabel: 'Последнее использование',
    revoke: 'Отозвать',
    revokeDialogTitle: 'Отозвать API‑ключ',
    revokeDialogDesc: 'Вы уверены, что хотите отозвать «{title}»? Это действие нельзя отменить, и все приложения, использующие этот ключ, перестанут работать.',
    revokeConfirm: 'Отозвать ключ',
    delete: 'Удалить',
    deleteDialogTitle: 'Удалить API‑ключ',
    deleteDialogDesc: 'Вы уверены, что хотите навсегда удалить «{title}»? Это действие нельзя отменить.',
    deleteConfirm: 'Удалить ключ',
    createdDialogTitle: 'API‑ключ создан',
    createdDialogDesc: 'Ваш API‑ключ успешно создан',
    createdDialogLabel: 'API‑ключ',
    createdDialogImportant: 'Важно:',
    createdDialogImportantText: 'Сохраните этот API‑ключ в надёжном месте. В целях безопасности мы не сможем показать его повторно.',
    close: 'Закрыть',
    sdkTitle: 'Kortix SDK и API',
    sdkDesc: 'Наш SDK и API сейчас в бете. Используйте эти ключи для интеграции с программным интерфейсом при создании кастомных приложений и автоматизаций.',
    sdkDocsLink: 'Документация SDK',
    betaBadge: 'Бета',
    toastCreateSuccess: 'API‑ключ успешно создан',
    toastCreateFailed: 'Не удалось создать API‑ключ',
    toastRevokeSuccess: 'API‑ключ успешно отозван',
    toastRevokeFailed: 'Не удалось отозвать API‑ключ',
    toastDeleteSuccess: 'API‑ключ успешно удалён',
    toastDeleteFailed: 'Не удалось удалить API‑ключ',
    toastCopied: '{what} скопирован в буфер обмена',
    toastCopyFailed: 'Не удалось скопировать {what}',
    toastCopiedFull: 'Полный API‑ключ скопирован в буфер обмена',
    toastCopyFullFailed: 'Не удалось скопировать полный API‑ключ',
  },
  settings: {
    title: 'Настройки',
    profile: 'Профиль',
    apiKeys: 'API‑ключи',
    integrations: 'Интеграции',
    saveSuccess: 'Настройки успешно сохранены',
  },
  credentials: {
    title: 'Доступы приложений',
  },
  checkout: {
    errorTitle: 'Ошибка оплаты',
    errorDesc: 'Не удалось загрузить форму оплаты',
    loadingText: 'Загрузка защищённой формы оплаты…',
    stripeSlowLoad: 'Система оплаты загружается слишком долго. Обновите страницу.',
    noSession: 'Сессия оплаты не найдена. Начните процесс оплаты заново.',
    stripeLoadFailed: 'Не удалось загрузить систему оплаты',
  },
  errors: {
    unknown: 'Неизвестная ошибка. Попробуйте ещё раз.',
    requiredField: 'Поле обязательно для заполнения',
    network: 'Ошибка сети. Проверьте соединение.',
    operationFailed: 'Операция не выполнена',
  },
} as const;

export type Copy = typeof copy;
export type CopySection = keyof Copy;

// Helper to safely access sections if needed in code
export const getCopy = () => copy;

export default copy;
