/* eslint-disable */
/**
 * Convex API Reference
 *
 * This file re-exports the generated API from the Convex backend.
 * The actual API types are generated by `npx convex dev` in the
 * apps/convex/convex/_generated/ directory.
 *
 * Usage:
 * ```ts
 * import { api } from "@/lib/convex/api";
 * const threads = useQuery(api.threads.list, { accountId });
 * ```
 */

// Re-export from the generated API in the convex app
// Note: This assumes the convex app's _generated files are available
// During build, these types are resolved from the convex backend deployment
export { api, internal } from "convex/_generated/api";
