apiVersion: v1
kind: Service
metadata:
  name: {{ include "kortix-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kortix-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kortix-api.selectorLabels" . | nindent 4 }}
